objects/Account.object
<CustomObject>
    <fields>
        <fullName>sf42_Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Territory_Sharing__c.object
<CustomObject>
    <fields>
        <fullName>Account_Access_Level__c</fullName>
        <label>Account Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <label>PT - Territory Sharing</label>
    <nameField>
        <label>Territory Sharing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Sharing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory_Sharing_Criterion__c.object
<CustomObject>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>equals</fullName>
                    <default>true</default>
                    <label>equals</label>
                </value>
                <value>
                    <fullName>includes</fullName>
                </value>
                <value>
                    <fullName>starts with</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory_Sharing__c</fullName>
        <label>Territory Sharing</label>
        <referenceTo>Territory_Sharing__c</referenceTo>
        <relationshipName>Territory_Sharing_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PT - Territory Sharing Criterion</label>
    <nameField>
        <displayFormat>TSC-{000000}</displayFormat>
        <label>Territory Sharing Criterion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Sharing Criterion</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>sf42_Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Dubai</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany - CM</fullName>
                </value>
                <value>
                    <fullName>Germany - Headquarters</fullName>
                </value>
                <value>
                    <fullName>Germany - NDT</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>Poland Technology</fullName>
                </value>
                <value>
                    <fullName>Poland Wibrem</fullName>
                </value>
                <value>
                    <fullName>Russia</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>Spain</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

globalValueSets/Access_Levels.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Edit</fullName>
        <default>true</default>
        <label>Read Write</label>
    </customValue>
    <customValue>
        <fullName>Read</fullName>
        <label>Read Only</label>
    </customValue>
    <customValue>
        <fullName>None</fullName>
        <label>No Access</label>
    </customValue>
    <masterLabel>Access Levels</masterLabel>
</GlobalValueSet>

classes/SelectOptionsHelper.cls
public with sharing class SelectOptionsHelper {

    public static List<SelectOption> getAccessLevelOptions() {
        
        List<SelectOption> accessLevelOptions = new List<SelectOption>();
        List<Schema.PicklistEntry> pickListValues = SObjectType.Territory_Sharing__c.fields.getMap().get('Account_Access_Level__c').getDescribe().getPicklistValues();
        
        for (Schema.PicklistEntry entry : pickListValues) {
        
            if (entry.isActive()) { 
                accessLevelOptions.add(new SelectOption(entry.getValue(), entry.getLabel()));
            }
        }
        return accessLevelOptions;
    }
    
    public static List<SelectOption> getAccountAccessLevelOptions() {
        
        List<SelectOption> accessLevelOptions = new List<SelectOption>();
        List<Schema.PicklistEntry> pickListValues = SObjectType.Territory_Sharing__c.fields.getMap().get('Account_Access_Level__c').getDescribe().getPicklistValues();
        
        for (Schema.PicklistEntry entry : pickListValues) {
        
            if (entry.isActive() && entry.getValue() != SharingConstants.DEFAULT_LEVEL_ACCESS) { 
                accessLevelOptions.add(new SelectOption(entry.getValue(), entry.getLabel()));
            }
        }
        return accessLevelOptions;
    }
    
    public static List<SelectOption> getGroupsOptions(Map<Id,String> groupNames) {
        List<SelectOption> groups = new List<SelectOption>();
        for (Id groupId : groupNames.keySet()) {
            groups.add(new SelectOption(groupId, groupNames.get(groupId)));   
        }
        return groups;
    }

    public static Map<Id, String> getPartnerExecutiveGroups() {

        Map<Id, String> groups = new Map<Id, String>();
        Map<Id, Id> userRoleGroups = new Map<Id, Id>();

        for (Group groupDetails : GroupSelector.getPartnerExecutiveGroups()) {
            userRoleGroups.put(groupDetails.RelatedId, groupDetails.Id);
        }

        for (UserRole role : GroupSelector.getGroupRoles(userRoleGroups.keySet())) {
                groups.put(userRoleGroups.get(role.Id), role.Name);
        }
        return groups;
    }

    public static List<SelectOption> getOperatorsOptions() {
                        
        List<SelectOption> operators = new List<SelectOption>();
        List<Schema.PicklistEntry> pickListValues = Schema.getGlobalDescribe().get('Territory_Sharing_Criterion__c').getDescribe().fields.getMap().get('Operator__c').getDescribe().getPicklistValues();

        for (Schema.PicklistEntry entry :pickListValues) {
                    
            if (entry.isActive()) {
                operators.add(new SelectOption(entry.getValue(), entry.getLabel()));
            }
        }
        return operators;
    }
    
    public static List<SelectOption> getBusinessUnitsOptions() {
        
        List<SelectOption> businessUnits = new List<SelectOption>();

        for (Schema.PicklistEntry entry : sObjectType.User.fields.getMap().get('sf42_Business_Unit__c').getDescribe().getPicklistValues()) {
            
            if (entry.isActive()) {
                businessUnits.add(new SelectOption(entry.getValue(), entry.getLabel()));
            }
        } 
        return businessUnits;
    }
    
    public static List<SelectOption> getCriteriaFieldsOptionsByObjectName(String objectName) {
        
        List<SelectOption> criteriaFields = new List<SelectOption>();
        List<String> fieldApiNames = SharingSettingsHelper.getCommonSharingFieldsByObjectName(objectName);  
        Map<String, String> apiNamesToLabels = getFieldLabelsByApiNames(objectName, fieldApiNames);
        
        for (String field : fieldApiNames) {
            criteriaFields.add(new SelectOption(field, apiNamesToLabels.get(field)));
        }
        return criteriaFields;
    }
    
     private static Map<String, String> getFieldLabelsByApiNames(String sObjectType, List<String> apiNames) {
         
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Schema.SObjectType typeOfObject = schemaMap.get(sObjectType);
        Map<String, Schema.SObjectField> fieldMap = typeOfObject.getDescribe().fields.getMap();
        Map<String, String> result = new Map<String, String>();
         
        for (String apiName : apiNames) {
            result.put(apiName, fieldMap.get(apiName).getDescribe().getLabel());
        }
        return result;
    }

    public static List<SelectOption> getPartnerAccountsByBusinessUnit(String businessUnit) {

        List<SelectOption> partnerAccounts = new List<SelectOption>();
		partnerAccounts.add(new SelectOption('', 'Select Partner Account'));     
        
        for (Account account : [
                SELECT Id, Name, isPartner
                FROM Account
                WHERE (isPartner = true AND
                    sf42_Business_Unit__c = :businessUnit)
                ORDER BY Name
                LIMIT 10000
            ]) {
            partnerAccounts.add(new SelectOption(account.Id, account.Name));
        }
        return partnerAccounts;
    }
}