objects/Account.object
<CustomObject>
    <fields>
        <fullName>Industry_subcategory__c</fullName>
        <label>Industry subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Agricultural machinery</fullName>
                </value>
                <value>
                    <fullName>Aircraft, aircraft parts</fullName>
                </value>
                <value>
                    <fullName>Air Force</fullName>
                </value>
                <value>
                    <fullName>Army</fullName>
                </value>
                <value>
                    <fullName>Banking</fullName>
                </value>
                <value>
                    <fullName>Biogas</fullName>
                </value>
                <value>
                    <fullName>Blowers, fans</fullName>
                </value>
                <value>
                    <fullName>Bottling plants</fullName>
                </value>
                <value>
                    <fullName>Breweries</fullName>
                </value>
                <value>
                    <fullName>Cardboard</fullName>
                </value>
                <value>
                    <fullName>Certification Bodies</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Coal</fullName>
                </value>
                <value>
                    <fullName>Colleges</fullName>
                </value>
                <value>
                    <fullName>Compressors</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Conveyors</fullName>
                </value>
                <value>
                    <fullName>Corrugated</fullName>
                </value>
                <value>
                    <fullName>Couplings</fullName>
                </value>
                <value>
                    <fullName>Cranes</fullName>
                </value>
                <value>
                    <fullName>Desalination plant</fullName>
                </value>
                <value>
                    <fullName>Diesel engines</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Environmental</fullName>
                </value>
                <value>
                    <fullName>Exploration - Offshore</fullName>
                </value>
                <value>
                    <fullName>Exploration - Onshore</fullName>
                </value>
                <value>
                    <fullName>Extruders</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sf42_gl_ALI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ALI</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/CM_CD_Serial_Number__c.object
<CustomObject>
    <description>Contains CD Serial numbers and Activation Codes pairs</description>
    <fields>
        <fullName>ptt_Activation_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Activation code in format 1234-1234-1234-1234</description>
        <label>Activation Code</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>PT - CM CD Serial Number</label>
    <nameField>
        <label>CD Serial No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM CD Serial Numbers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CM_Custom_Package__c.object
<CustomObject>
    <description>This object hold complete packages created by users from features.</description>
    <fields>
        <fullName>ptt_IdCode__c</fullName>
        <description>Format VIB x.yyy</description>
        <inlineHelpText>Format VIB x.yyy</inlineHelpText>
        <label>Material item number</label>
        <length>13</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ptt_System__c</fullName>
        <description>System (device, software) name.</description>
        <label>System</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Calimaster</fullName>
                </value>
                <value>
                    <fullName>VIBGUARD Viewer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ptt_Variant__c</fullName>
        <description>Specific sub type of system. It is allowed to select more than one as package can fit for more variants.</description>
        <label>Variant</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>ptt_System__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Server</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PT - CM Custom Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Custom Packages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CM_Feature_Item__c.object
<CustomObject>
    <description>Hold all available features.</description>
    <fields>
        <fullName>ptt_Code__c</fullName>
        <description>Code in format XXXX_ZZZ</description>
        <label>Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ptt_Is_Multiorder__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Multi order packages can be ordered more than one. Non multi order may be ordered only once.</inlineHelpText>
        <label>Is Multiorder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ptt_Key__c</fullName>
        <label>Key</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ptt_System__c</fullName>
        <label>System</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Calimaster</fullName>
                </value>
                <value>
                    <fullName>VIBGUARD Viewer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ptt_Variant__c</fullName>
        <label>Variant</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>ptt_System__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Server</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PT - CM Feature Item</label>
    <nameField>
        <label>Feature Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Feature Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ptt_cm_End_User__c.object
<CustomObject>
    <fields>
        <fullName>ptt_CM_Order__c</fullName>
        <label>CM Order</label>
        <referenceTo>ptt_cm_Order__c</referenceTo>
        <relationshipLabel>CM End Users</relationshipLabel>
        <relationshipName>CM_End_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ptt_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ptt_Industry__c</fullName>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Automation</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Cement</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Converting</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Facilities</fullName>
                </value>
                <value>
                    <fullName>Food &amp; Beverage</fullName>
                </value>
                <value>
                    <fullName>Machine Manufacturers</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Marine &amp; Shipping</fullName>
                </value>
                <value>
                    <fullName>Metal</fullName>
                </value>
                <value>
                    <fullName>Mining</fullName>
                </value>
                <value>
                    <fullName>Oil &amp; Gas</fullName>
                </value>
                <value>
                    <fullName>Petro chemical</fullName>
                </value>
                <value>
                    <fullName>Power Generation</fullName>
                </value>
                <value>
                    <fullName>Printing</fullName>
                </value>
                <value>
                    <fullName>Public Sector</fullName>
                </value>
                <value>
                    <fullName>Pulp and Paper</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Wood Industry</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ptt_Street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ptt_Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PT - CM End User</label>
    <nameField>
        <label>End User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM End Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ptt_cm_Order__c.object
<CustomObject>
    <fields>
        <fullName>ptt_Activation_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Activation Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ptt_CD_Serial_Number__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CD Serial Number</label>
        <referenceTo>CM_CD_Serial_Number__c</referenceTo>
        <relationshipLabel>CM Orders</relationshipLabel>
        <relationshipName>CM_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_ProductID__c</fullName>
        <label>ProductID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ptt_Sales_Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Channel</label>
        <referenceTo>ptt_cm_Sales_Channel__c</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_System__c</fullName>
        <label>System</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Calimaster</fullName>
                </value>
                <value>
                    <fullName>VIBGUARD Viewer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ptt_Variant__c</fullName>
        <label>Variant</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ptt_System__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Server</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PT - CM Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ptt_cm_Sales_Channel__c.object
<CustomObject>
    <description>Sales Channel for CM</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CM Sales Channels</relationshipLabel>
        <relationshipName>Sales_Channels</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PT - CM Sales Channel</label>
    <nameField>
        <label>Sales Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Sales Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/as_TestHelper.cls
public class as_TestHelper {
    
    /* Account */
    public static Account createTestAccount(boolean makeinsert) {
        Account a = new Account();
        a.Name = 'testaccount ' + String.valueOf(Math.random()).substring(0,4);
        a.Phone = '+12-34-56789-0';
        a.sf42_gl_ALI__c = TRUE;
        a.CurrencyIsoCode = 'EUR';
        a.Industry = 'Chemicals';
        a.Industry_subcategory__c = 'Other';
        a.BillingCountry = 'Germany';
        a.BillingPostalCode = '51-180';
        
        if (makeinsert) insert a;
        return a;
    }
    
    /* CM Sales Channel */
    public static ptt_cm_Sales_Channel__c createCmSalesChannel (boolean makeinsert) {
        Account a = createTestAccount(TRUE);
        ptt_cm_Sales_Channel__c record = new ptt_cm_Sales_Channel__c();
        // Reqired fields
        record.Account_Name__c = a.Id; 
        // Optional fileds
        
        if (makeinsert) insert record;
        return record;
    }
    
    /*  CM Custom Package */
    public static CM_Custom_Package__c createCmCustomPackage (boolean makeinsert) {
        CM_Custom_Package__c record = new CM_Custom_Package__c();
        record.ptt_System__c = 'VIBGUARD Viewer';
        record.ptt_Variant__c = 'Server';
        record.ptt_IdCode__c = 'VIB 6.' + String.valueOf(Math.random()).substring(3,6);
        record.Name = 'My test Package';
            
        if (makeinsert) insert record;
        return record;
    }
    
    /* CM Feature Item */
    public static CM_Feature_Item__c createCmFeatureItem(boolean makeinsert) {
        CM_Feature_Item__c record = new CM_Feature_Item__c();
        record.ptt_Code__c = 'VIB 2.' + String.valueOf(Math.random()).substring(3,6);
        record.ptt_Is_Multiorder__c = TRUE;
        record.ptt_Key__c = 'VGDV_TEST';
        record.ptt_System__c = 'VIBGUARD Viewer';
        record.ptt_Variant__c = 'Server';
            
        if (makeinsert) insert record;
        return record;
    }
    
    /* CM CD Srial Number */
    public static CM_CD_Serial_Number__c createCmCDSerialNumber(boolean makeinsert) {
        CM_CD_Serial_Number__c record = new CM_CD_Serial_Number__c();
        record.Name = '00'+ String.valueOf(Math.random()).substring(3,6);
        record.ptt_Activation_Code__c = 'R842-Q8CA-47HO-C' +  + String.valueOf(Math.random()).substring(3,6);
            
        if (makeinsert) insert record;
        return record;
    }
    
    /* CM Order */
    public static ptt_cm_Order__c createCmOrder (boolean makeinsert) {
        ptt_cm_Sales_Channel__c sc = createCmSalesChannel(TRUE);
        ptt_cm_Order__c record = new ptt_cm_Order__c();
        // Reqired fields
        record.ptt_System__c = 'VIBGUARD Viewer';
        // Optional fields
        record.ptt_Sales_Channel__c = sc.Id;
        record.ptt_Variant__c = 'Server';
        record.ptt_CD_Serial_Number__c = createCDSerialNo(TRUE).Id;
        record.ptt_ProductID__c = '123456789';
            
        if (makeinsert) insert record;
        return record;
    }
    
    /* CD Serial No */
    public static CM_CD_Serial_Number__c createCDSerialNo (boolean makeinsert) {
    	CM_CD_Serial_Number__c record = new CM_CD_Serial_Number__c();
    	record.Name = '00' + String.valueOf(Math.random()).substring(3,6);
    	record.ptt_Activation_Code__c = 'Q81M-PZ30-XKI1-4' + String.valueOf(Math.random()).substring(3,6);
    	if (makeinsert) insert record;
        return record;
    }

    /* End User data */
    public static ptt_cm_End_User__c createCmEndUserData(boolean makeinsert) {
        ptt_cm_End_User__c record = new ptt_cm_End_User__c();
        record.Name = 'Pruftechnik';
        record.ptt_Street__c = 'Street';
        record.ptt_Email__c = 'p.wozniak@pruftechnik.com.pl';
        record.ptt_Zip_Postal_Code__c = '51-180';
        record.ptt_Industry__c = 'Automotive';
        record.ptt_City__c = 'Wroclaw';
        record.ptt_Industry_subcategory__c = 'Other';
        record.ptt_State__c = 'dolnoslaskie';
        record.ptt_Country2__c = 'Poland';   
        record.ptt_CM_Order__c = createCmOrder(TRUE).Id;
            
        if (makeinsert) insert record;
        return record;
    }
    
    /* End User data for given Order*/
    public static ptt_cm_End_User__c createCmEndUserDataForGivenOrder(Id orderId, boolean makeinsert) {
        ptt_cm_End_User__c record = createCmEndUserData(FALSE);
        record.ptt_CM_Order__c = orderId;
            
        if (makeinsert) insert record;
        return record;
    }
    
    /*** Macros ***/
    public static ptt_cm_Order__c  createOrderWithEndUser (boolean makeinsert){
        ptt_cm_Order__c o = createCmOrder(TRUE);
        ptt_cm_End_User__c eu = createCmEndUserDataForGivenOrder(o.Id, TRUE);
        return o;
    }
    
    public static ptt_cm_Order__c  createActiveOrderWithPackages (boolean makeinsert){
    	// Create custom package
    	createCmCustomPackage(TRUE);
    	
    	
    	ptt_cm_Order__c o = createCmOrder(TRUE);
    	return o;
    }
    
}