objects/Account_Owner_Sharing__c.object
<CustomObject>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Account_Owner_Sharings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PT Account Owner Sharing</label>
    <nameField>
        <label>Account Owner Sharing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Owner Sharings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountOwnerSharingHelper.cls
/**
 * Created by yanagerasimchuk on 6/11/18.
 */

public with sharing class AccountOwnerSharingHelper {
    
    public static Boolean isDuplicate(Account_Owner_Sharing__c sharing) {
        Boolean isDuplicate = false;
        Map<Id, Account_Owner_Sharing__c> duplicateSharings = AccountOwnerSharingSelector.getSharingMapByPartnerAccountId(sharing.Partner_Account__c);
		System.debug(duplicateSharings);
        if (sharing.Id != null) {
            duplicateSharings.remove(sharing.Id);
        }
        if (!duplicateSharings.isEmpty()) {
            isDuplicate = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'This Sharing is duplicate.'));
        }
        return isDuplicate;
    }

    public static Boolean ruleNameIsBlank(String ruleName) {
        Boolean isBlank = false;
        if (String.isBlank(ruleName)) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Rule Name is blank.'));
            isBlank = true;
        }
        return isBlank;
    }
}