objects/Account.object
<CustomObject>
    <fields>
        <fullName>ptt_tax_number__c</fullName>
        <description>Fiscal ID - Tax number</description>
        <inlineHelpText>Number which account use for tax/fiscal purposes.</inlineHelpText>
        <label>Tax number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sf42_Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>sf42_gl_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <infoMessage>By default this list is limited to Account contacts&apos;.
You can see all results by clicking on &quot;Show all results&quot; below.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities.</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Order_Processing__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Processing</relationshipLabel>
        <relationshipName>Order_Processing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Order Processing</relationshipLabel>
        <relationshipName>Order_Processing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Order Processing</relationshipLabel>
        <relationshipName>Order_Processing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_Tax_number__c</fullName>
        <description>Spain</description>
        <label>Tax number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sf42_JP_Order_Amount__c</fullName>
        <label>Order Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>PT - Order Processing</label>
    <nameField>
        <displayFormat>OP# {000000}</displayFormat>
        <label>OP-Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Processing</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>sf42_Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Dubai</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany - CM</fullName>
                </value>
                <value>
                    <fullName>Germany - Headquarters</fullName>
                </value>
                <value>
                    <fullName>Germany - NDT</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>Poland Technology</fullName>
                </value>
                <value>
                    <fullName>Poland Wibrem</fullName>
                </value>
                <value>
                    <fullName>Russia</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>Spain</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/pt_OrderProcessingController.cls
public with sharing class pt_OrderProcessingController {

    /****************************************/
    /***** Controller global variables ******/
    /****************************************/
    // Constants

    // Variables
    private Order_Processing__c OrderProcObj; //Object for standard controller
    ApexPages.StandardController stdController; // Standard controller
    String oppid = '';
    Opportunity oppObj = new Opportunity();
    
    // Variables with default get set methods
    public Account accountObj { get; set; } 
    public boolean addressRead { get; set; } 
    public boolean showAllSections { get; set; }
    
    /****************************************/
    /**** Custom controller constructor *****/
    /****************************************/

    public pt_OrderProcessingController(ApexPages.StandardController controller) {
        this.stdController = controller;
        this.OrderProcObj = (Order_Processing__c)stdController.getRecord();
        oppid = ApexPages.currentPage().getParameters().get('oppid');
        addressRead = FALSE;
        
        if (oppid != null) {
            oppObj = [SELECT Id, AccountId, sf42_gl_Contact__c, CurrencyIsoCode, Amount  FROM Opportunity WHERE id = :oppid];
            OrderProcObj.Opportunity__c = oppObj.Id;
            OrderProcObj.Account__c = oppObj.AccountId;
            OrderProcObj.Contact__c = oppObj.sf42_gl_Contact__c;
            OrderProcObj.CurrencyIsoCode = oppObj.CurrencyIsoCode;
            OrderProcObj.sf42_JP_Order_Amount__c = oppObj.Amount;
            doReadAccountAddresses();
        }
        
        if ([SELECT sf42_Business_Unit__c FROM User Where Id = :Userinfo.getUserId()].sf42_Business_Unit__c == 'Spain') {
             showAllSections = TRUE;
        } 
    }
    
    /********** Immediate actions ***********/
    /***** Actions executed on page load ****/
    /****************************************/
       
    
    /************** Getters *****************/
    /*** Passing values to VS Page fields ***/
    /****************************************/
    
    
    /************* Setters *****************/
    /***** Reading values from field *******/
    /***************************************/

    
    
    /************** Buttons *****************/
    /** Actions invoked by custom buttons ***/
    /****************************************/
    
    public PageReference doReadAccountAddresses() {
        String AccountId = OrderProcObj.Account__c;
        // ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING, AccountId));
        if (AccountId != null) {
            accountObj = [SELECT Id, ptt_tax_number__c, BillingCity, BillingCountry, BillingState, BillingStreet, BillingPostalCode, ShippingCity, ShippingCountry, ShippingState, ShippingStreet, ShippingPostalCode
                          FROM Account 
                          WHERE Id = :AccountId];
            addressRead = TRUE;
            OrderProcObj.ptt_Tax_number__c = accountObj.ptt_tax_number__c;
        }
        return null;
    }
    
    public PageReference opSave() {
        /*if(addressRead == TRUE) {
                accountObj.dupcheck__dc3DisableDuplicateCheck__c = TRUE;
            update accountObj;
        }*/
        upsert OrderProcObj;
        PageReference pr = new PageReference('/' + OrderProcObj.Id );
        pr.setRedirect(true);
        return pr;
        
    }
    
    
    /****************************************/
    /**** Class specific helper functions ***/
    /****************************************/
    


}