objects/Account_Owner_Sharing__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Access_Level__c</fullName>
        <label>Activity Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Device_Access_Level__c</fullName>
        <label>Device Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Account_Owner_Sharings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Services_Demos_Access_Level__c</fullName>
        <label>Services Demos Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <label>PT Account Owner Sharing</label>
    <nameField>
        <label>Account Owner Sharing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Owner Sharings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Access_Levels.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Edit</fullName>
        <default>true</default>
        <label>Read Write</label>
    </customValue>
    <customValue>
        <fullName>Read</fullName>
        <label>Read Only</label>
    </customValue>
    <customValue>
        <fullName>None</fullName>
        <label>No Access</label>
    </customValue>
    <masterLabel>Access Levels</masterLabel>
</GlobalValueSet>

classes/AccountOwnerSharingSelector.cls
/**
 * Created by yanagerasimchuk on 6/15/18.
 */

public with sharing class AccountOwnerSharingSelector {

    public static Map<Id, Account_Owner_Sharing__c> getSharingsByPartnerAccountIds(List<Id> accountIds) {

        Map<Id, Account_Owner_Sharing__c> ownerBasedSharings = new Map<Id, Account_Owner_Sharing__c>();

        for (Account_Owner_Sharing__c sharing: [
                SELECT Id, Partner_Account__c,
                Services_Demos_Access_Level__c, Activity_Access_Level__c, Device_Access_Level__c
                FROM Account_Owner_Sharing__c
                WHERE Partner_Account__c IN :accountIds
                LIMIT 100000
            ]) {
            ownerBasedSharings.put(sharing.Partner_Account__c, sharing);
        }
        return ownerBasedSharings;
    }

    public static List<Account_Owner_Sharing__c> getSharingByPartnerAccountId(Id accountId) {
        return [
                SELECT Activity_Access_Level__c
                FROM Account_Owner_Sharing__c
                WHERE Partner_Account__c = :accountId
                LIMIT 2
        ];
    }

    public static Map<Id, Account_Owner_Sharing__c> getSharingMapByPartnerAccountId(Id accountId) {
        return new Map<Id, Account_Owner_Sharing__c>([
                SELECT Activity_Access_Level__c
                FROM Account_Owner_Sharing__c
                WHERE Partner_Account__c = :accountId
                LIMIT 2
        ]);
    }
}