objects/Account_Owner_Sharing__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Access_Level__c</fullName>
        <label>Activity Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Device_Access_Level__c</fullName>
        <label>Device Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Services_Demos_Access_Level__c</fullName>
        <label>Services Demos Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <label>PT Account Owner Sharing</label>
    <nameField>
        <label>Account Owner Sharing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Owner Sharings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory_Sharing__c.object
<CustomObject>
    <fields>
        <fullName>Account_Access_Level__c</fullName>
        <label>Account Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Activity_Access_Level__c</fullName>
        <label>Activity Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Access_Level__c</fullName>
        <label>Case Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Access_Level__c</fullName>
        <label>Contact Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Device_Access_Level__c</fullName>
        <label>Device Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group_Id_To_Share_Record_With__c</fullName>
        <description>Role Id of portal user to share found records with</description>
        <label>Group Id To Share With</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Access_Level__c</fullName>
        <label>Lead Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Access_Level__c</fullName>
        <label>Opportunity Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Services_Demos_Access_Level__c</fullName>
        <label>Services Demos Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <label>PT - Territory Sharing</label>
    <nameField>
        <label>Territory Sharing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Sharing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Access_Levels.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Edit</fullName>
        <default>true</default>
        <label>Read Write</label>
    </customValue>
    <customValue>
        <fullName>Read</fullName>
        <label>Read Only</label>
    </customValue>
    <customValue>
        <fullName>None</fullName>
        <label>No Access</label>
    </customValue>
    <masterLabel>Access Levels</masterLabel>
</GlobalValueSet>

classes/SharingWrapper.cls
/**
 * Created by yanagerasimchuk on 5/25/18.
 */

public with sharing class SharingWrapper {
	
    public Id customSharingRuleId { get; private set;}
    public Set<Id> usersOrGroupId { get; private set;}
    public String accountAccessLevel { get; private set;}
    public String leadAccessLevel { get; private set;}
    public String contactAccessLevel { get; private set;}
    public String opportunityAccessLevel { get; private set;}
    public String caseAccessLevel { get; private set;}
    public String deviceAccessLevel { get; private set;}
    public String servicesDemosAccessLevel { get; private set;}
    public String activityAccessLevel { get; private set;}
    
    public SharingWrapper(Territory_Sharing__c sharing) {
        this.customSharingRuleId = sharing.Id;
        this.usersOrGroupId = new Set<Id>();
        this.usersOrGroupId.add(sharing.Group_Id_To_Share_Record_With__c);
        this.accountAccessLevel = sharing.Account_Access_Level__c;
        this.leadAccessLevel = sharing.Lead_Access_Level__c;
        this.contactAccessLevel = sharing.Contact_Access_Level__c;
        this.opportunityAccessLevel = sharing.Opportunity_Access_Level__c;
        this.caseAccessLevel = sharing.Case_Access_Level__c;
        this.deviceAccessLevel = sharing.Device_Access_Level__c;
        this.servicesDemosAccessLevel = sharing.Services_Demos_Access_Level__c;
        this.activityAccessLevel = sharing.Activity_Access_Level__c;
    }

    public SharingWrapper(Account_Owner_Sharing__c sharing, Set<Id> userIds) {
        this.customSharingRuleId = sharing.Id;
        this.usersOrGroupId = new Set<Id>();
        this.usersOrGroupId.addAll(userIds);
        this.deviceAccessLevel = sharing.Device_Access_Level__c;
        this.servicesDemosAccessLevel = sharing.Services_Demos_Access_Level__c;
        this.activityAccessLevel = sharing.Activity_Access_Level__c;
        this.accountAccessLevel = SharingConstants.DEFAULT_LEVEL_ACCESS;
        this.leadAccessLevel = SharingConstants.DEFAULT_LEVEL_ACCESS;
    }
}