objects/Account.object
<CustomObject>
    <fields>
        <fullName>sf42_Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>sf42_Business_Unit__c</fullName>
        <label>Business Unit Contact</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ptt_Bussines_Unit_formula__c</fullName>
        <formula>IF ( TEXT(Owner:User.sf42_Business_Unit__c)  &lt;&gt;  &apos;&apos;, TEXT(Owner:User.sf42_Business_Unit__c),
   /* ALL Countries without not divided for CM,ALI,NDT */

      IF (CONTAINS(Owner:Queue.QueueName, &quot;Belgium&quot;), &quot;Belgium&quot;,
      IF (CONTAINS(Owner:Queue.QueueName, &quot;Brazil&quot;), &quot;Brazil&quot;,
      IF (CONTAINS(Owner:Queue.QueueName, &quot;North America&quot;), &quot;North America&quot;,
      IF (CONTAINS(Owner:Queue.QueueName, &quot;China&quot;), &quot;China&quot;,
      IF (CONTAINS(Owner:Queue.QueueName, &quot;Dubai&quot;), &quot;Dubai&quot;,
      IF (CONTAINS(Owner:Queue.QueueName, &quot;France&quot;), &quot;France&quot;,
      IF (CONTAINS(Owner:Queue.QueueName, &quot;Italy&quot;), &quot;Italy&quot;,
      IF (CONTAINS(Owner:Queue.QueueName, &quot;Japan&quot;), &quot;Japan&quot;,
      IF (CONTAINS(Owner:Queue.QueueName, &quot;Poland&quot;), &quot;Poland&quot;,
      IF (CONTAINS(Owner:Queue.QueueName, &quot;Russia&quot;), &quot;Russia&quot;,
      IF (CONTAINS(Owner:Queue.QueueName, &quot;Singapore&quot;), &quot;Singapore&quot;,
      IF (CONTAINS(Owner:Queue.QueueName, &quot;Spain&quot;), &quot;Spain&quot;,
      IF (CONTAINS(Owner:Queue.QueueName, &quot;Turkey&quot;), &quot;Turkey&quot;,
      IF (CONTAINS(Owner:Queue.QueueName, &quot;United Kingdom&quot;), &quot;UK&quot;,
      IF (CONTAINS(Owner:Queue.QueueName, &quot;North America - Sales Leads&quot;), &quot;North America&quot;,
      

   /* ALI QUEUES */ 
   IF (CONTAINS(Owner:Queue.QueueName, &quot;ALI&quot;),
      IF (CONTAINS(Owner:Queue.QueueName, &quot;Germany&quot;), &quot;Germany - CM&quot;, 
      IF (CONTAINS(Owner:Queue.QueueName, &quot;International Sales&quot;), &quot;Inter. - ALI&quot;,

   &quot;ALI Other&quot;)),
 
   /* CM QUEUES */
   IF (CONTAINS(Owner:Queue.QueueName, &quot;CM&quot;),
      IF (CONTAINS(Owner:Queue.QueueName, &quot;Germany&quot;), &quot;Germany - CM&quot;,
      IF (CONTAINS(Owner:Queue.QueueName, &quot;International Sales&quot;), &quot;Inter. - CM&quot;,

   &quot;CM Other&quot;)),


   /* NDT QUEUES */
   IF (CONTAINS(Owner:Queue.QueueName, &quot;NDT&quot;),
      IF (CONTAINS(Owner:Queue.QueueName, &quot;Germany&quot;), &quot;Germany - NDT&quot;,
      IF (CONTAINS(Owner:Queue.QueueName, &quot;International Sales&quot;), &quot;Inter. - NDT&quot;,
  
   &quot;NDT Other&quot;)),

   &quot;Other&quot;)))))))))))))))))))</formula>
        <inlineHelpText>Business unit of current owner.</inlineHelpText>
        <label>Business Unit.</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sf42_Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Service_and_Demontration__c.object
<CustomObject>
    <fields>
        <fullName>sf42_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Customer.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services &amp; Demos</relationshipLabel>
        <relationshipName>Services_and_Demontrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PT - Services &amp; Demos</label>
    <nameField>
        <displayFormat>SD# {00000}</displayFormat>
        <label>Services &amp; Demos</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services &amp; Demos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/sf42_Devices__c.object
<CustomObject>
    <fields>
        <fullName>sf42_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Company which bought this device.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Devices</relationshipLabel>
        <relationshipName>Devices</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>PT - Device</label>
    <nameField>
        <label>Item No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sharing_Logger__c.object
<CustomObject>
    <fields>
        <fullName>Territory_Sharing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory Sharing</label>
        <referenceTo>Territory_Sharing__c</referenceTo>
        <relationshipLabel>Sharing Loggers</relationshipLabel>
        <relationshipName>Sharing_Loggers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PT - Sharing Logger</label>
    <nameField>
        <displayFormat>TSLN-{0000000}</displayFormat>
        <label>Territory Sharing Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sharing Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory_Sharing__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Access_Level__c</fullName>
        <label>Activity Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Device_Access_Level__c</fullName>
        <label>Device Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Services_Demos_Access_Level__c</fullName>
        <label>Services Demos Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <label>PT - Territory Sharing</label>
    <nameField>
        <label>Territory Sharing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Sharing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory_Sharing_Criterion__c.object
<CustomObject>
    <fields>
        <fullName>Territory_Sharing__c</fullName>
        <label>Territory Sharing</label>
        <referenceTo>Territory_Sharing__c</referenceTo>
        <relationshipName>Territory_Sharing_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PT - Territory Sharing Criterion</label>
    <nameField>
        <displayFormat>TSC-{000000}</displayFormat>
        <label>Territory Sharing Criterion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Sharing Criterion</pluralLabel>
    <recordTypes>
        <fullName>Account_Criteria</fullName>
        <active>true</active>
        <description>Territory sharing criteria for Account object</description>
        <label>Account Criteria</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lead_Criteria</fullName>
        <active>true</active>
        <description>Territory sharing criteria for Lead object</description>
        <label>Lead Criteria</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Access_Levels.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Edit</fullName>
        <default>true</default>
        <label>Read Write</label>
    </customValue>
    <customValue>
        <fullName>Read</fullName>
        <label>Read Only</label>
    </customValue>
    <customValue>
        <fullName>None</fullName>
        <label>No Access</label>
    </customValue>
    <masterLabel>Access Levels</masterLabel>
</GlobalValueSet>

classes/SharingConstants.cls
public with sharing class SharingConstants {

    //Object name and fiedls
    public static final String LOGGER_OBJECT_NAME = 'Sharing_Logger__c';
    public static final String SHARING_CRITERIA_OBJECT_NAME = 'Territory_Sharing_Criterion__c';
    public static final String TERRITORY_SHARING_OBJECT_NAME = 'Territory_Sharing__c';
    public static final String DEVICES_OBJECT = 'sf42_Devices__c';
    public static final String SERVICE_DEMOS_OBJECT = 'Service_and_Demontration__c';
    public static final String ACCOUNT_OBJECT = 'Account';
    public static final String LEAD_OBJECT = 'Lead';
    public static final String IS_PARTNER_ACCOUNT_FIELD = 'isPartner';
    public static final String OWNER_ID_FIELD = 'OwnerId';

    //Record Typed
    public static final String LEAD_CRITERIA = 'Lead_Criteria';
    public static final String ACCOUNT_CRITERIA = 'Account_Criteria';
    public static final String TERRITORY_SHARING_RECORD_TYPE = 'Territory_Sharing';

    //BATCH OPERATIONS
    public static final String ADD_OPERATION = 'add';
    public static final String UPDATE_OPERATION = 'update';
    public static final String DELETE_OPERATION = 'delete';

    //ACCESS LEVELS
    public static final String DEFAULT_LEVEL_ACCESS = 'None';
    public static final String VIEW_LEVEL_ACCESS = 'Read';
    public static final String EDIT_LEVEL_ACCESS = 'Edit';

    public static final Map<String, Integer> ACCESS_LEVEL_PRIORITY = new Map<String, Integer>{
    	EDIT_LEVEL_ACCESS => 2,
        VIEW_LEVEL_ACCESS => 1,
        DEFAULT_LEVEL_ACCESS => 0    
    };
        
    //Group and Portal Roles Constants
    public static final String EXECUTIVE_PORTAL_ROLE = 'Executive';
    public static final String PARTNER_PORTAL_TYPE = 'Partner';
    public static final String ROLE_AND_SUBORDINATES_GROUP_TYPE = 'RoleAndSubordinates';

    public static final List<String> ACCOUNT_OWNER_FIELDS = new List<String> {
            'Name',
            'Partner_account__r.sf42_Business_Unit__c',
            'Partner_account__c',
            'Device_Access_Level__c',
            'Services_Demos_Access_Level__c',
            'Activity_Access_Level__c'
    };

    public static Map<String, String> BUSINESS_UNIT_FIELD_BY_OBJECT = new Map<String, String>{
            LEAD_OBJECT => 'ptt_Bussines_Unit_formula__c',
            ACCOUNT_OBJECT => 'sf42_Business_Unit__c'
    };

    public static Map<String, String> ACCOUNT_LOOKUP_FIELD_BY_CHILD_OBJECT = new Map<String, String>{
            'Opportunity' => 'AccountId',
            'Case' => 'AccountId',
            'Contact' => 'AccountId',
            'sf42_Devices__c' => 'sf42_Account__c',
            'Service_and_Demontration__c' => 'sf42_Account__c'
    };

    public static final Map<String, String> OBJECT_BY_CRITERIA_TYPE = new Map<String, String> {
            LEAD_CRITERIA => LEAD_OBJECT,
            ACCOUNT_CRITERIA => ACCOUNT_OBJECT
    };

    public static final Map<String, String> CRITERIA_TYPE_BY_OBJECT = new Map<String, String> {
            LEAD_OBJECT => LEAD_CRITERIA ,
            ACCOUNT_OBJECT => ACCOUNT_CRITERIA
    };
        
    //Includes and Equals operators have the same logic (by Przemyslaw's request)
    public static final Map<String,String> OPERATION_CLASS_BY_OBJECT = new Map<String,String> {
            'equals' => 'IncludesOperator',
            'includes' => 'IncludesOperator',
            'starts with' => 'StartsWithOperator'
    };

    public static final Map<String, String> LOGICAL_OPERATOR_BY_OPERATION = new Map<String, String>{
            'equals' => 'IN',
            'includes' => 'IN',
            'starts with' => 'LIKE'
    };

    public static final Map<String, String> SHARING_RECALCULATION_CLASS_BY_OBJECT = new Map<String, String> {
            ACCOUNT_OBJECT  => 'AccountSharingRecalculation',
            LEAD_OBJECT => 'LeadSharingRecalculation'
    };

    public static final Map<String, Map<String, String>> CRITERIA_TO_OPERATION_TO_LABEL = new Map<String, Map<String, String>> {
            ACCOUNT_CRITERIA => new Map<String, String> {
                    ADD_OPERATION => Label.Added_Accounts_Success,
                    UPDATE_OPERATION => Label.Updated_Accounts_Success,
                    DELETE_OPERATION => Label.Deleted_Accounts_Success
            },
            LEAD_CRITERIA => new Map<String, String> {
                    ADD_OPERATION => Label.Added_Leads_Success,
                    UPDATE_OPERATION => Label.Updated_Leads_Success,
                    DELETE_OPERATION => Label.Deleted_Leads_Success
            }
    };
 
    public static final Map<String, String> OWNER_BASED_SHARINGS_LABEL_BY_OPERATION = new Map<String, String> {
		ADD_OPERATION => Label.Added_Owner_Based_Rules ,
		UPDATE_OPERATION => Label.Updated_Owner_Based_Rules,
		DELETE_OPERATION => Label.Deleted_Owner_Based_Rules 
    };
}