objects/CM_Activation_Log__c.object
<CustomObject>
    <fields>
        <fullName>ptt_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CM Activation Logs</relationshipLabel>
        <relationshipName>CM_Activation_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_Activation__c</fullName>
        <label>Activation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ptt_Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ptt_cm_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CM Order</label>
        <referenceTo>ptt_cm_Order__c</referenceTo>
        <relationshipLabel>CM Activation Logs</relationshipLabel>
        <relationshipName>CM_Activation_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_do_Reset__c</fullName>
        <defaultValue>false</defaultValue>
        <label>do Reset</label>
        <type>Checkbox</type>
    </fields>
    <label>PT - CM Activation Log</label>
    <nameField>
        <displayFormat>AL-{00000}</displayFormat>
        <label>CM Activation Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Activation Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ptt_cm_Order__c.object
<CustomObject>
    <fields>
        <fullName>ptt_Activation_Counter__c</fullName>
        <label>Activation Counter</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ptt_Sales_Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Channel</label>
        <referenceTo>ptt_cm_Sales_Channel__c</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PT - CM Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ptt_cm_Sales_Channel__c.object
<CustomObject>
    <description>Sales Channel for CM</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CM Sales Channels</relationshipLabel>
        <relationshipName>Sales_Channels</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PT - CM Sales Channel</label>
    <nameField>
        <label>Sales Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Sales Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/as_ResetActivationCounter.cls
public with sharing class as_ResetActivationCounter {

    /****************************************/
    /***** Controller global variables ******/
    /****************************************/
    
    // Variables
    private String orderId = '';
    private ptt_cm_Order__c cmOrderObject;
    private Integer oldActivationValue = 0;
        
    // Variables with default get set methods
    public String CommentText { get; set; }
    public String orderName { get; set; }

    /****************************************/
    /**** Custom controller constructor *****/
    /****************************************/
    
    public as_ResetActivationCounter() {
        orderId = ApexPages.currentPage().getParameters().get('orderid');
        cmOrderObject = [SELECT Name, ptt_Activation_Counter__c, ptt_Sales_Channel__r.Account_Name__c FROM ptt_cm_Order__c WHERE Id = :orderId];
        orderName = cmOrderObject.Name;
        oldActivationValue = Integer.ValueOf (cmOrderObject.ptt_Activation_Counter__c);
    }

    /************** Buttons *****************/
    /** Actions invoked by custom buttons ***/
    /****************************************/
     
    /* Reset */
    public PageReference doReset() {
        if (CommentText == '') {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO, 'Comment field cannot be empty'));
            return null;
        } else {
        
            // Set activation counter to 0
            cmOrderObject.ptt_Activation_Counter__c = 0;
            update cmOrderObject;
        
            // Create Log entry
            CM_Activation_Log__c alog = new CM_Activation_Log__c();
            alog.ptt_Account__c =  cmOrderObject.ptt_Sales_Channel__r.Account_Name__c;
            alog.ptt_do_Reset__c = TRUE;
            alog.ptt_Activation__c = oldActivationValue;
            alog.ptt_cm_Order__c = OrderId;
            alog.ptt_Comment__c = CommentText;                                         
            insert alog;
     
            PageReference pr = Page.asEditOrder;
            pr.getParameters().put('Id', orderId);
            pr.setRedirect(false);
            return pr;
        }
    }    

    /* Back */
    public PageReference Back() {
        PageReference pr = Page.asEditOrder;
        pr.getParameters().put('Id', orderId);
        pr.setRedirect(false);
        return pr;
    }
}