objects/CM_Activation_Log__c.object
<CustomObject>
    <fields>
        <fullName>ptt_Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ptt_End_User_Data__c</fullName>
        <label>End User Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ptt_cm_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CM Order</label>
        <referenceTo>ptt_cm_Order__c</referenceTo>
        <relationshipLabel>CM Activation Logs</relationshipLabel>
        <relationshipName>CM_Activation_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PT - CM Activation Log</label>
    <nameField>
        <displayFormat>AL-{00000}</displayFormat>
        <label>CM Activation Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Activation Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ptt_cm_End_User__c.object
<CustomObject>
    <fields>
        <fullName>ptt_CM_Order__c</fullName>
        <label>CM Order</label>
        <referenceTo>ptt_cm_Order__c</referenceTo>
        <relationshipLabel>CM End Users</relationshipLabel>
        <relationshipName>CM_End_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ptt_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ptt_Company_Name__c</fullName>
        <label>Company Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ptt_Country2__c</fullName>
        <label>Country2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ptt_CountryISO2__c</fullName>
        <description>Two letters Country Iso code</description>
        <label>Country ISO Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ptt_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ptt_Industry__c</fullName>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Automation</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Cement</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Converting</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Facilities</fullName>
                </value>
                <value>
                    <fullName>Food &amp; Beverage</fullName>
                </value>
                <value>
                    <fullName>Machine Manufacturers</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Marine &amp; Shipping</fullName>
                </value>
                <value>
                    <fullName>Metal</fullName>
                </value>
                <value>
                    <fullName>Mining</fullName>
                </value>
                <value>
                    <fullName>Oil &amp; Gas</fullName>
                </value>
                <value>
                    <fullName>Petro chemical</fullName>
                </value>
                <value>
                    <fullName>Power Generation</fullName>
                </value>
                <value>
                    <fullName>Printing</fullName>
                </value>
                <value>
                    <fullName>Public Sector</fullName>
                </value>
                <value>
                    <fullName>Pulp and Paper</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Wood Industry</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ptt_Industry_subcategory__c</fullName>
        <label>Industry subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ptt_Industry__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Agricultural machinery</fullName>
                </value>
                <value>
                    <fullName>Aircraft, aircraft parts</fullName>
                </value>
                <value>
                    <fullName>Air Force</fullName>
                </value>
                <value>
                    <fullName>Army</fullName>
                </value>
                <value>
                    <fullName>Banking</fullName>
                </value>
                <value>
                    <fullName>Biogas</fullName>
                </value>
                <value>
                    <fullName>Blowers, fans</fullName>
                </value>
                <value>
                    <fullName>Bottling plants</fullName>
                </value>
                <value>
                    <fullName>Breweries</fullName>
                </value>
                <value>
                    <fullName>Cardboard</fullName>
                </value>
                <value>
                    <fullName>Certification Bodies</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Coal</fullName>
                </value>
                <value>
                    <fullName>Colleges</fullName>
                </value>
                <value>
                    <fullName>Compressors</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Conveyors</fullName>
                </value>
                <value>
                    <fullName>Corrugated</fullName>
                </value>
                <value>
                    <fullName>Couplings</fullName>
                </value>
                <value>
                    <fullName>Cranes</fullName>
                </value>
                <value>
                    <fullName>Desalination plant</fullName>
                </value>
                <value>
                    <fullName>Diesel engines</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Environmental</fullName>
                </value>
                <value>
                    <fullName>Exploration - Offshore</fullName>
                </value>
                <value>
                    <fullName>Exploration - Onshore</fullName>
                </value>
                <value>
                    <fullName>Extruders</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ptt_State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ptt_Street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ptt_Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PT - CM End User</label>
    <nameField>
        <label>End User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM End Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ptt_cm_Order__c.object
<CustomObject>
    <fields>
        <fullName>ptt_Activation_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Activation Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ptt_Activation_Counter__c</fullName>
        <label>Activation Counter</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ptt_End_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to End user</description>
        <label>End User</label>
        <referenceTo>ptt_cm_End_User__c</referenceTo>
        <relationshipLabel>CM Orders</relationshipLabel>
        <relationshipName>CM_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ptt_ProductID__c</fullName>
        <label>ProductID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ptt_Sales_Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Channel</label>
        <referenceTo>ptt_cm_Sales_Channel__c</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PT - CM Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ptt_cm_Sales_Channel__c.object
<CustomObject>
    <description>Sales Channel for CM</description>
    <fields>
        <fullName>ptt_remote_access__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Remote access</label>
        <type>Checkbox</type>
    </fields>
    <label>PT - CM Sales Channel</label>
    <nameField>
        <label>Sales Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Sales Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/pw_cc__CountryObject__c.object
<CustomObject>
</CustomObject>

classes/as_UpdateEndUserData_controller.cls
public class as_UpdateEndUserData_controller {

    /****************************************/
    /***** Controller global variables ******/
    /****************************************/
    
    // Variables
    String user, pwd, license, actcode, enduser;
    String company, street, zip, city, state, country, email, industry; 
    static ptt_cm_Order__c orderDetails = new ptt_cm_Order__c();
    static Map<String,String> enduserData = new Map<String,String>{};

    
    // Variables with default get set methods   
    public String redirectionURL { get; set; }

    /****************************************/
    /**** Custom controller constructor *****/
    /****************************************/

    public as_UpdateEndUserData_controller(ApexPages.StandardController controller) {
        // Read all parameters.
        user = as_licenseGenerator.ptUrlDecode(ApexPages.currentPage().getParameters().get('user'));
        pwd = as_licenseGenerator.ptUrlDecode(ApexPages.currentPage().getParameters().get('pwd'));      
        
        license = as_licenseGenerator.ptUrlDecode(ApexPages.currentPage().getParameters().get('license'));
        actcode = as_licenseGenerator.ptUrlDecode(ApexPages.currentPage().getParameters().get('actcode'));
        enduser = as_licenseGenerator.ptUrlDecode(ApexPages.currentPage().getParameters().get('enduser'));

        enduserData = extractEndUserData(enduser);    
    }
    
    /****************************************/
    /********** Immediate actions ***********/
    /****************************************/
    
    public Pagereference doUpdateEndUserData() {   
      // Create Log entry
        CM_Activation_Log__c alog = new CM_Activation_Log__c();
        alog.ptt_Comment__c = 'Incoming request call from vibguard';                                     
        alog.ptt_End_User_Data__c = 'RAW: ' + ApexPages.currentPage().getParameters().get('enduser') + '\nDecoded: ' + enduser ;
        insert alog;
      
        try {
	        if (as_vibguardInterface_controller.verifyVibLogin(user, pwd) == TRUE) {
	            if(reqiredParametersSent() == TRUE) {
                	orderDetails = readOrderDetails(actcode);
                	as_licenseGenerator.generatePackagesParameterValue(orderDetails.Id);         
	                if (orderDetails.ptt_Activation_Counter__c > 2) { 
	                	throw new as_Exceptions.licGenException('ACTIVATION_LIMIT_REACHED.', 'Please contact PRUFTECHNIK to reset activation counter.' );     
	                } else if (orderDetails.ptt_is_Active__c == FALSE) {
            			throw new as_Exceptions.licGenException ('ORDER_IS_NOT_ACTIVE', 'Please contact PRUFTECHNIK to activate an order.' ); 	               
                    } else {
                        updateEndUserData(orderDetails);                       
                        redirectionURL = '/apex/asvibguardInterface?user=' +  user + '&pwd=' + pwd + '&license=' + license + '&actcode=' + actcode + '&tid=' + as_licenseGenerator.getTransactionTan().Id;                        
                        return null;
                    }                 
	            }
	        }	        
        	return null;
        }
        catch (as_Exceptions.licGenException ex) {
	        as_licenseGenerator.asErrorMessage (ex.getMessage(), ex.getDetails());
	        return null;
        }  
    }
    
    /****************************************/
    /*** Class specific helper functions ****/
    /****************************************/
    
    ptt_cm_Order__c readOrderDetails(String actcode){
        // Find Order details for given Activation Code.
        try {
            orderDetails = [SELECT Id, ptt_End_User__c, ptt_Sales_Channel__r.ptt_remote_access__c, ptt_Sales_Channel__c, ptt_Activation_Code__c, ptt_Activation_Counter__c, ptt_is_Active__c
                            FROM ptt_cm_Order__c  
                            WHERE ptt_Activation_Code__c = :actcode LIMIT 1];
            return orderDetails;
        }
        catch (exception e) {
            throw new as_Exceptions.licGenException ('ACTIVATION_CODE_NOT_FOUND', 'Order with given Activation code not found');
        } 
    }
    
    /**
    *  Check if license, actcode parameters are not empty
    *  @return FALSE when any of them empty, TRUE when all contains data
    */
    boolean reqiredParametersSent () {
        if( (license == null || license == '' || actcode == null || actcode == '' || enduser == null || enduser == '' || !enduserData.containsKey('company') || !enduserData.containsKey('email') || !enduserData.containsKey('street') || !enduserData.containsKey('zip') || !enduserData.containsKey('city') || !enduserData.containsKey('country'))) {
            throw new as_Exceptions.licGenException ('MISSING_PARAMETERS', 'Missing required parameters.');
            return FALSE;
        }
        return TRUE;
    }   
    
    /**
    *  Update enduser data based on given order object.
    *  @param cmOrderObject - order object
    *
    */
    void updateEndUserData(ptt_cm_Order__c cmOrderObject) {
        ptt_cm_End_User__c endUser = new ptt_cm_End_User__c();
        
        // check if there is connected endUserData record then update it
        if (cmOrderObject.ptt_End_User__c != null) {
            endUser = [SELECT Id, Name, ptt_Company_Name__c, ptt_City__c, ptt_CM_Order__c, ptt_Country2__c, ptt_Email__c, ptt_Industry__c, ptt_Industry_subcategory__c, ptt_State__c, ptt_Street__c, ptt_Zip_Postal_Code__c 
                       FROM ptt_cm_End_User__c 
                       WHERE Id = :cmOrderObject.ptt_End_User__c];  
        }   
        // If any enduser data are filled in no update
        if (EndUser.ptt_Company_Name__c != null || EndUser.ptt_Street__c != null || EndUser.ptt_Email__c != null || 
        	 EndUser.ptt_Zip_Postal_Code__c != null || EndUser.ptt_City__c != null || EndUser.ptt_Country2__c != null ||
        	 endUser.ptt_State__c != null || endUser.ptt_Industry__c != null) {
        	 // Do not update enduser data but update Product Id
        	 cmOrderObject.ptt_ProductID__c =  license;
             update (cmOrderObject);        	 
        	 
        } else {
            // Requred parameters
            if (enduserData.containsKey('company')) {endUser.ptt_Company_Name__c = enduserData.get('company');}
            if (enduserData.containsKey('email')) {endUser.ptt_Email__c = enduserData.get('email');}
            if (enduserData.containsKey('street')) {endUser.ptt_Street__c = enduserData.get('street');}
            if (enduserData.containsKey('zip')) {endUser.ptt_Zip_Postal_Code__c = enduserData.get('zip');}
            if (enduserData.containsKey('city')) {endUser.ptt_City__c = enduserData.get('city');}       
            if (enduserData.containsKey('country')) {endUser.ptt_CountryISO2__c = enduserData.get('country');}   
            if (enduserData.containsKey('country')) {endUser.ptt_Country2__c = getCountryNameFromISO2(enduserData.get('country'));}
            
            // Optional Parameters
            if (enduserData.containsKey('state')) {endUser.ptt_State__c = enduserData.get('state');} else {endUser.ptt_State__c = null;}
            if (enduserData.containsKey('industry')) {endUser.ptt_Industry__c = enduserData.get('industry');} else {endUser.ptt_Industry__c = null;}
            if (enduserData.containsKey('subindustry')) endUser.ptt_Industry_subcategory__c = enduserData.get('subindustry');           
            
            // Order Id
            endUser.ptt_CM_Order__c = cmOrderObject.Id;
            upsert(endUser);
            
            cmOrderObject.ptt_End_User__c = endUser.id;
            cmOrderObject.ptt_ProductID__c =  license;
            update (cmOrderObject);
       	}
    }
    
    String getCountryNameFromISO2 (String iso2Code) {
        String countryname = '';
        try {
            countryName = [SELECT Name FROM pw_cc__CountryObject__c WHERE pw_cc__IsoCode_2__c = :iso2Code Limit 1].Name;
        }
        catch (exception e) {
            countryName = iso2Code;
        }   
        return countryName;
    }
    
    /**
    *  Extract data from endueser paremter and splits them by category name.
    *  @allParams string with enduser data parameter
    *  @return Map of parameters like name=>John, city=>Wroclaw
    */
    Map<String, String> extractEndUserData (String allParams) {
        Map<String, String> paramMap = new Map<String,String>{};
        if(allParams != null && allParams != '' && allParams.contains('|')){        
            // Remove three pipes ||| and parameter name if parameter is empty
            allParams = allParams.replaceAll('(\\w)*\\|\\|\\|','');
            // Split by sub parameters of enduser
            List<String> tmp = allParams.split('\\|\\|');
            for ( String t : tmp ) {
                String key = t.substring(0,t.indexOf('|')).toLowerCase();
                String value = t.substring(t.indexOf('|')+1,t.length());
                paramMap.put(key, value);         
            } 
        }      
        return paramMap;
    }   
    
}