objects/CM_Custom_Package__c.object
<CustomObject>
    <description>This object hold complete packages created by users from features.</description>
    <fields>
        <fullName>ptt_IdCode__c</fullName>
        <description>Format VIB x.yyy</description>
        <inlineHelpText>Format VIB x.yyy</inlineHelpText>
        <label>Material item number</label>
        <length>13</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ptt_Index__c</fullName>
        <label>Index</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PT - CM Custom Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Custom Packages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CM_Selected_Package__c.object
<CustomObject>
    <description>This is a link object which links Orders and Custom Packages</description>
    <fields>
        <fullName>ptt_CM_Custom_Package__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Relation to selected Custom Package</description>
        <label>CM Custom Package</label>
        <referenceTo>CM_Custom_Package__c</referenceTo>
        <relationshipName>CM_Selected_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_CM_Order__c</fullName>
        <label>CM Order</label>
        <referenceTo>ptt_cm_Order__c</referenceTo>
        <relationshipName>CM_Selected_Packages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ptt_Index__c</fullName>
        <label>Index</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ptt_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>PT - CM Selected Package</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>CM Selected Packages Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Selected Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ptt_cm_End_User__c.object
<CustomObject>
    <fields>
        <fullName>ptt_CM_Order__c</fullName>
        <label>CM Order</label>
        <referenceTo>ptt_cm_Order__c</referenceTo>
        <relationshipLabel>CM End Users</relationshipLabel>
        <relationshipName>CM_End_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ptt_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ptt_Company_Name__c</fullName>
        <label>Company Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ptt_Country2__c</fullName>
        <label>Country2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ptt_CountryISO2__c</fullName>
        <description>Two letters Country Iso code</description>
        <label>Country ISO Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ptt_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ptt_Industry__c</fullName>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Automation</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Cement</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Converting</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Facilities</fullName>
                </value>
                <value>
                    <fullName>Food &amp; Beverage</fullName>
                </value>
                <value>
                    <fullName>Machine Manufacturers</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Marine &amp; Shipping</fullName>
                </value>
                <value>
                    <fullName>Metal</fullName>
                </value>
                <value>
                    <fullName>Mining</fullName>
                </value>
                <value>
                    <fullName>Oil &amp; Gas</fullName>
                </value>
                <value>
                    <fullName>Petro chemical</fullName>
                </value>
                <value>
                    <fullName>Power Generation</fullName>
                </value>
                <value>
                    <fullName>Printing</fullName>
                </value>
                <value>
                    <fullName>Public Sector</fullName>
                </value>
                <value>
                    <fullName>Pulp and Paper</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Wood Industry</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ptt_Industry_subcategory__c</fullName>
        <label>Industry subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ptt_Industry__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Agricultural machinery</fullName>
                </value>
                <value>
                    <fullName>Aircraft, aircraft parts</fullName>
                </value>
                <value>
                    <fullName>Air Force</fullName>
                </value>
                <value>
                    <fullName>Army</fullName>
                </value>
                <value>
                    <fullName>Banking</fullName>
                </value>
                <value>
                    <fullName>Biogas</fullName>
                </value>
                <value>
                    <fullName>Blowers, fans</fullName>
                </value>
                <value>
                    <fullName>Bottling plants</fullName>
                </value>
                <value>
                    <fullName>Breweries</fullName>
                </value>
                <value>
                    <fullName>Cardboard</fullName>
                </value>
                <value>
                    <fullName>Certification Bodies</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Coal</fullName>
                </value>
                <value>
                    <fullName>Colleges</fullName>
                </value>
                <value>
                    <fullName>Compressors</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Conveyors</fullName>
                </value>
                <value>
                    <fullName>Corrugated</fullName>
                </value>
                <value>
                    <fullName>Couplings</fullName>
                </value>
                <value>
                    <fullName>Cranes</fullName>
                </value>
                <value>
                    <fullName>Desalination plant</fullName>
                </value>
                <value>
                    <fullName>Diesel engines</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Environmental</fullName>
                </value>
                <value>
                    <fullName>Exploration - Offshore</fullName>
                </value>
                <value>
                    <fullName>Exploration - Onshore</fullName>
                </value>
                <value>
                    <fullName>Extruders</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ptt_State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ptt_Street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ptt_Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PT - CM End User</label>
    <nameField>
        <label>End User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM End Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ptt_cm_Order__c.object
<CustomObject>
    <fields>
        <fullName>ptt_Activation_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Activation Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ptt_Activation_Counter__c</fullName>
        <label>Activation Counter</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ptt_End_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to End user</description>
        <label>End User</label>
        <referenceTo>ptt_cm_End_User__c</referenceTo>
        <relationshipLabel>CM Orders</relationshipLabel>
        <relationshipName>CM_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ptt_Sales_Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Channel</label>
        <referenceTo>ptt_cm_Sales_Channel__c</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PT - CM Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/as_editOrderController.cls
public with sharing class as_editOrderController {

    /****************************************/
    /***** Controller global variables ******/
    /****************************************/
    // Constants
    Static final Integer ACTIVATION_COUNTER_LIMIT = 3;
    
    // Variables
    ApexPages.StandardController stdController; // Standard controller
    private ptt_cm_Order__c cmOrderObj = new ptt_cm_Order__c(); //cm Order Object
    List<CM_Selected_Package__c> packagesTableContent = new List<CM_Selected_Package__c>();
    
    private Id endUserId ;
    
    // Automatic get set
    public ptt_cm_End_User__c cmEndUserObj {get; set;} 
    public CM_Selected_Package__c cmPackage {get; set;}
    public Boolean isEdit {get; set;}
    public String selectedPackageId {get; set;}
    public String isCreateLicenseDisabled {get; set;}
    public Integer activePackages {get; set;}

    
    /****************************************/
    /**** Custom controller constructor *****/
    /****************************************/
    
    public as_editOrderController(ApexPages.StandardController controller) {
        this.stdController = controller;
        this.cmOrderObj = (ptt_cm_Order__c)stdController.getRecord();     
        this.endUserId = cmOrderObj.ptt_End_User__c;
        
        readData();
    }   
    
    /* 
    * Reads data from database. 
    * Made as separate function because after save constructor is not called.
    */ 
    void readData() {
        // Read data from CM End User if user is already specified
        if (endUserId != null) {
        cmEndUserObj = [SELECT Id, Name, ptt_Company_Name__c, ptt_Street__c, ptt_Email__c, ptt_Zip_Postal_Code__c, ptt_Industry__c, ptt_City__c, ptt_Industry_subcategory__c, ptt_State__c, ptt_Country2__c, ptt_CountryISO2__c
                        FROM ptt_cm_End_User__c 
                        WHERE id = :cmOrderObj.ptt_End_User__c];            
        } else {
        	cmEndUserObj = new ptt_cm_End_User__c();
        }           
        
        // Get a list of packages assigned for this order                
        packagesTableContent = [SELECT id, Name, ptt_IsActive__c, ptt_Index__c, ptt_CM_Custom_Package__c, ptt_CM_Custom_Package__r.Name, ptt_CM_Custom_Package__r.ptt_IdCode__c
                        FROM CM_Selected_Package__c
                        WHERE ptt_CM_Order__c = :cmOrderObj.Id
                        ORDER BY Name];                
       
        activePackages = [SELECT COUNT()
                         FROM CM_Selected_Package__c
                         WHERE ptt_CM_Order__c = :cmOrderObj.Id AND ptt_IsActive__c = TRUE ];
        
    }
    
    
    /************** Getters *****************/
    /*** Passing values to VS Page fields ***/
    /****************************************/

    public List<CM_Selected_Package__c> getPackagesTableContent() {                                      
        return this.packagesTableContent;
    }

    /************** Buttons *****************/
    /** Actions invoked by custom buttons ***/
    /****************************************/

    /* Save */
    public PageReference orderSave() {
        update packagesTableContent;
        updateCmOrder(cmOrderObj);  

        // If user fill in one of reqired fields validate if all has values.
        final String validationError = 'Please fill in all reqired fields.';
        Boolean err = FALSE;
        if ( cmEndUserObj.ptt_Company_Name__c != null || cmEndUserObj.ptt_Street__c != null || cmEndUserObj.ptt_Email__c != null || 
        	 cmEndUserObj.ptt_Zip_Postal_Code__c != null || cmEndUserObj.ptt_City__c != null || cmEndUserObj.ptt_Country2__c != null) {
        	    if (cmEndUserObj.ptt_Company_Name__c == null) {cmEndUserObj.ptt_Company_Name__c.addError(validationError); err = TRUE;}
        		if (cmEndUserObj.ptt_Street__c == null ) {cmEndUserObj.ptt_Street__c.addError(validationError); err = TRUE;}
        		if (cmEndUserObj.ptt_Email__c == null) {cmEndUserObj.ptt_Email__c.addError(validationError); err = TRUE;}
        		if (cmEndUserObj.ptt_Zip_Postal_Code__c == null) {cmEndUserObj.ptt_Zip_Postal_Code__c.addError(validationError); err = TRUE;}
        		if (cmEndUserObj.ptt_City__c == null ) {cmEndUserObj.ptt_City__c.addError(validationError); err = TRUE;}
        		if (cmEndUserObj.ptt_Country2__c == null) {cmEndUserObj.ptt_Country2__c.addError(validationError); err = TRUE;}
        	if (err == TRUE) {return null;}			
        }        
        
        // Insert user data if there is no associated EndUser object yet
        if (endUserId == null) {
            cmEndUserObj.Name = cmOrderObj.Name;
            cmEndUserObj.ptt_CM_Order__c = cmOrderObj.Id;
			cmEndUserObj.ptt_CountryISO2__c = findISO2(cmEndUserObj.ptt_Country2__c);
            insert cmEndUserObj;
            
            cmOrderObj.ptt_End_User__c = cmEndUserObj.Id;
            endUserId = cmEndUserObj.Id;
            updateCmOrder(cmOrderObj);         
  
        }
        // Otherwise update already existing record (record is read in cosntructor to display values on page)
        else if (endUserId != null ) { 
            cmEndUserObj.ptt_CountryISO2__c = findISO2(cmEndUserObj.ptt_Country2__c);    
            update cmEndUserObj;
            updateCmOrder(cmOrderObj);     
        }
        
        readData();      
        this.cmOrderObj.ptt_Activation_Code__c = [SELECT ptt_Activation_Code__c FROM ptt_cm_Order__c WHERE Id = :cmOrderObj.Id].ptt_Activation_Code__c;        
        return null;
    }
    
    /* Back */
    public PageReference orderEditBack() {
        PageReference pr = Page.asSalesChannelDetails;
        pr.getParameters().put('Id', cmOrderObj.ptt_Sales_Channel__c);
        return pr;
    }
    
    /* Create License */
    public PageReference doCreateLicense() {
        // Check if order is active
        if (cmOrderObj.ptt_Is_Active__c == TRUE) {
                // Check if 
                if (cmOrderObj.ptt_Activation_Counter__c > (ACTIVATION_COUNTER_LIMIT-1) ) {     
                String errorMsg = 'Activation limit reached, you can not create more licenses';
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING, errorMsg));
             }
        } else {
            String errorMsg = 'Order is inactive you can not create license';
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING, errorMsg));
        }   
        PageReference pr = Page.asCreateLicense;
        pr.getParameters().put('orderId', cmOrderObj.Id);
        pr.setRedirect(true);
        return pr;
    }
    
    /* Reset */
    public PageReference doResetCounter() {
        PageReference pr = Page.asResetCounter;
        pr.getParameters().put('orderId', cmOrderObj.Id);
        pr.setRedirect(false);
        return pr;
    }
    
    /* Details */
    public PageReference doEditOrderNumbers() {
		orderSave();
		if (ApexPages.hasMessages() == TRUE) {return null;}
        PageReference pr = Page.asEditOrderNumbers;
        pr.getParameters().put('orderId', cmOrderObj.Id);
        return pr;
     }
    
    /* Add */
    public PageReference doAddPackage() {
    	orderSave();
		if (ApexPages.hasMessages() == TRUE) {return null;}
        PageReference pr = Page.asAddCustomPackage;
        pr.getParameters().put('orderId', cmOrderObj.Id);
        return pr;
    }
    
    /*********** Command links **************/
    /*** Actions invoked by comand links ****/
    /****************************************/

    /* Del */
    public PageReference doDeletePackage() {
        Database.Delete(selectedPackageId);
        readData();
        return null;
    }
   
    /****************************************/
    /**** Class specific helper functions ***/
    /****************************************/
    
    /**
    * Updates Cm Order in case of duplicated SerialNo display error 
    * @since 1.1
    * @param cmOrderObj reference to cmOrder object
    */
    void updateCmOrder(ptt_cm_Order__c cmOrderObj){
        try {
            update cmOrderObj;          
        } catch (exception e) {
            cmOrderObj.ptt_CD_Serial_Number__c.addError('This CD Serial Number is already used, plese check it again.');
        } 
    } 
    
    /**
    * Search for ISO2 code by selected country.
    * @since 1.1
    * @param countryName string with selected country name.
    * @return two letters country ISO code  
    */
    String findISO2(String countryName) {
	    String ISO2 = '';
	    try {
	    	ISO2 = [SELECT pw_cc__IsoCode_2__c FROM pw_cc__CountryObject__c WHERE Name = :countryName].pw_cc__IsoCode_2__c;
	    } catch (exception e) {}  
	    return ISO2;
    }
}