objects/CM_CD_Serial_Number__c.object
<CustomObject>
    <description>Contains CD Serial numbers and Activation Codes pairs</description>
    <label>PT - CM CD Serial Number</label>
    <nameField>
        <label>CD Serial No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM CD Serial Numbers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CM_Custom_Package__c.object
<CustomObject>
    <description>This object hold complete packages created by users from features.</description>
    <fields>
        <fullName>ptt_Index__c</fullName>
        <label>Index</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ptt_Quantity__c</fullName>
        <label>Quantity</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PT - CM Custom Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Custom Packages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CM_Feature_Item__c.object
<CustomObject>
    <description>Hold all available features.</description>
    <fields>
        <fullName>ptt_Quantity__c</fullName>
        <description>For temporary storage in apex class, do no fill any data.</description>
        <inlineHelpText>For temporary storage in apex class, do no fill any data.</inlineHelpText>
        <label>Quantity</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PT - CM Feature Item</label>
    <nameField>
        <label>Feature Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Feature Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CM_Selected_Feature__c.object
<CustomObject>
    <description>Holds data about selected features for Custom Packages</description>
    <fields>
        <fullName>ptt_CM_Custom_Package__c</fullName>
        <label>CM Custom Package</label>
        <referenceTo>CM_Custom_Package__c</referenceTo>
        <relationshipLabel>CM Selected Features</relationshipLabel>
        <relationshipName>CM_Selected_Features</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ptt_CM_Feature_Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Relation to feature item</description>
        <label>CM Feature Item</label>
        <referenceTo>CM_Feature_Item__c</referenceTo>
        <relationshipLabel>CM Selected Features</relationshipLabel>
        <relationshipName>CM_Selected_Features</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_Quantity__c</fullName>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PT - CM Selected Feature</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>CM Selected Feature Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Selected Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CM_Selected_Package__c.object
<CustomObject>
    <description>This is a link object which links Orders and Custom Packages</description>
    <fields>
        <fullName>ptt_CM_Custom_Package__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Relation to selected Custom Package</description>
        <label>CM Custom Package</label>
        <referenceTo>CM_Custom_Package__c</referenceTo>
        <relationshipName>CM_Selected_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_CM_Order__c</fullName>
        <label>CM Order</label>
        <referenceTo>ptt_cm_Order__c</referenceTo>
        <relationshipName>CM_Selected_Packages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ptt_Index__c</fullName>
        <label>Index</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ptt_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>PT - CM Selected Package</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>CM Selected Packages Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Selected Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ptt_cm_End_User__c.object
<CustomObject>
    <fields>
        <fullName>ptt_CM_Order__c</fullName>
        <label>CM Order</label>
        <referenceTo>ptt_cm_Order__c</referenceTo>
        <relationshipLabel>CM End Users</relationshipLabel>
        <relationshipName>CM_End_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>PT - CM End User</label>
    <nameField>
        <label>End User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM End Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ptt_cm_Order__c.object
<CustomObject>
    <fields>
        <fullName>ptt_Activation_Counter__c</fullName>
        <label>Activation Counter</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ptt_CD_Serial_Number__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CD Serial Number</label>
        <referenceTo>CM_CD_Serial_Number__c</referenceTo>
        <relationshipLabel>CM Orders</relationshipLabel>
        <relationshipName>CM_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_End_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to End user</description>
        <label>End User</label>
        <referenceTo>ptt_cm_End_User__c</referenceTo>
        <relationshipLabel>CM Orders</relationshipLabel>
        <relationshipName>CM_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ptt_ProductID__c</fullName>
        <label>ProductID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ptt_Sales_Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Channel</label>
        <referenceTo>ptt_cm_Sales_Channel__c</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PT - CM Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ptt_cm_Sales_Channel__c.object
<CustomObject>
    <description>Sales Channel for CM</description>
    <label>PT - CM Sales Channel</label>
    <nameField>
        <label>Sales Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Sales Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/as_CreateLicenseController_Test.cls
@isTest
public with sharing class as_CreateLicenseController_Test {
	 	 
	public static testMethod void test_as_CreateLicenseController() {
 
     	// Create Sales Channel
		ptt_cm_Sales_Channel__c sc = as_TestHelper.createCmSalesChannel(TRUE);
		
		// Crete end user data
		ptt_cm_End_User__c eud = as_TestHelper.createCmEndUserData(TRUE);
		
		// Insert CD Serial number
		CM_CD_Serial_Number__c csn = as_TestHelper.createCmCDSerialNumber(TRUE);
		
		// Insert order
		ptt_cm_Order__c cmo1 = as_TestHelper.createCmOrder(FALSE);
		cmo1.ptt_Sales_Channel__c = sc.Id;
		cmo1.ptt_End_User__c = eud.Id;
		cmo1.ptt_CD_Serial_Number__c = csn.Id;
		cmo1.ptt_ProductID__c = '123456789';
		cmo1.ptt_Is_Active__c = TRUE;
		cmo1.ptt_Activation_Counter__c = 0;
		insert cmo1;
		
		// Create custom package
		CM_Custom_Package__c cp = as_TestHelper.createCmCustomPackage(TRUE);
		
		// Link Package against Order
		CM_Selected_Package__c selpkg = new CM_Selected_Package__c();
		selpkg.ptt_CM_Custom_Package__c = cp.Id;
		selpkg.ptt_CM_Order__c = cmo1.Id;
		selpkg.ptt_IsActive__c = TRUE;
		selpkg.ptt_Index__c = 1;
		insert selpkg;
		
		// Create Feature item
		CM_Feature_Item__c fi = as_TestHelper.createCmFeatureItem(TRUE);
		
		CM_Selected_Feature__c sf = new CM_Selected_Feature__c();
		sf.ptt_CM_Custom_Package__c = cp.Id;
		sf.ptt_CM_Feature_Item__c = fi.id;
		sf.ptt_Quantity__c = 2;
		insert sf;
		       
		PageReference pageRef = Page.asCreateLicense;
        Test.setCurrentPage(pageRef);
		pageRef.getParameters().put('orderId', cmo1.Id); 
    	
		as_CreateLicenseController controller = new as_CreateLicenseController();
	
        
	    Test.setMock(HttpCalloutMock.class, new as_CreateLicenseControllerMock());

	    Test.startTest();

		// Create license button
		controller.CommentText = 'Test license create';
		System.assertEquals(null, controller.CreateLic());

		Test.stopTest();

		// Back button
		System.assertEquals('/apex/aseditorder?Id=' + cmo1.Id, controller.Back().getUrl() );
		
		// Check if Order is not active
		cmo1.ptt_Is_Active__c = FALSE;
		controller.CommentText = 'Test license create';
		controller.CreateLic();
	}
}