objects/CM_Custom_Package__c.object
<CustomObject>
    <description>This object hold complete packages created by users from features.</description>
    <fields>
        <fullName>ptt_IdCode__c</fullName>
        <description>Format VIB x.yyy</description>
        <inlineHelpText>Format VIB x.yyy</inlineHelpText>
        <label>Material item number</label>
        <length>13</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ptt_System__c</fullName>
        <description>System (device, software) name.</description>
        <label>System</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Calimaster</fullName>
                </value>
                <value>
                    <fullName>VIBGUARD Viewer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ptt_Variant__c</fullName>
        <description>Specific sub type of system. It is allowed to select more than one as package can fit for more variants.</description>
        <label>Variant</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>ptt_System__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Server</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ptt_isMultiorder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isMultiorder</label>
        <type>Checkbox</type>
    </fields>
    <label>PT - CM Custom Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Custom Packages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/as_CustomPackageManagement_Controller.cls
public with sharing class as_CustomPackageManagement_Controller {

    /****************************************/
    /***** Controller global variables ******/
    /****************************************/
    private CM_Custom_Package__c custPackageObj; //Object for standard controller
    ApexPages.StandardController stdController;
   
    // Automatic get set
    public String packageIdToDelete {get; set;}
    public String packageItemNoToDelete {get; set;}
   
    /****************************************/
    /**** Custom controller constructor *****/
    /****************************************/

    public as_CustomPackageManagement_Controller(ApexPages.StandardController controller) {
        this.stdController = controller;
        this.custPackageObj = (CM_Custom_Package__c)stdController.getRecord();
    }
    
    
    /*************** Getters ****************/
    /*** Passing values to VS Page fields ***/
    /****************************************/
        
    public List<CM_Custom_Package__c> getPackagesTableContent() {
        List<CM_Custom_Package__c> packagesList;
        if (custPackageObj.ptt_system__c == null) {
            packagesList = [SELECT Id, name, ptt_IdCode__c, ptt_System__c, ptt_variant__c, ptt_isMultiorder__c 
                            FROM CM_Custom_Package__c
                            ORDER BY ptt_IdCode__c ASC];
                            
        // Removed because it should                             
        /* } else if (custPackageObj.ptt_system__c != null && custPackageObj.ptt_variant__c == null) {
             packagesList = [SELECT Id, name, ptt_IdCode__c, ptt_System__c, ptt_variant__c, ptt_isMultiorder__c 
                             FROM CM_Custom_Package__c
                             WHERE ptt_system__c = :custPackageObj.ptt_system__c
                             ORDER BY ptt_IdCode__c ASC];*/
        } else if (custPackageObj.ptt_system__c != null ) { //&& custPackageObj.ptt_variant__c != null ) {
              packagesList = [SELECT Id, name, ptt_IdCode__c, ptt_System__c, ptt_variant__c, ptt_isMultiorder__c 
                             FROM CM_Custom_Package__c
                             WHERE ptt_system__c = :custPackageObj.ptt_system__c
                             AND ptt_variant__c = :custPackageObj.ptt_variant__c
                             ORDER BY ptt_IdCode__c ASC];
        
        }
        return packagesList;
    }
    
    /*************** Buttons ****************/
    /*** Actions invoked by custom buttons **/
    /****************************************/
    
    /* Filter */
    public PageReference doFilterPackages() {
        return null;
    }

    
    /*********** Command links **************/
    /*** Actions invoked by comand links ****/
    /****************************************/
    
    public PageReference doDeletePackage() {
        // Check if used in any order
        try {Database.delete(packageIdToDelete);}
        catch (System.DmlException e) {
        	ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING, 'Package ' + packageItemNoToDelete + ' can\'t be deleted because is selected in order(s). Remove it from orders(s) first.'));
        }
        return null;
    }

}