objects/CM_CD_Serial_Number__c.object
<CustomObject>
    <description>Contains CD Serial numbers and Activation Codes pairs</description>
    <fields>
        <fullName>ptt_Activation_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Activation code in format 1234-1234-1234-1234</description>
        <label>Activation Code</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>PT - CM CD Serial Number</label>
    <nameField>
        <label>CD Serial No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM CD Serial Numbers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CM_Selected_Package__c.object
<CustomObject>
    <description>This is a link object which links Orders and Custom Packages</description>
    <fields>
        <fullName>ptt_CM_Order__c</fullName>
        <label>CM Order</label>
        <referenceTo>ptt_cm_Order__c</referenceTo>
        <relationshipName>CM_Selected_Packages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PT - CM Selected Package</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>CM Selected Packages Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Selected Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ptt_cm_End_User__c.object
<CustomObject>
    <fields>
        <fullName>ptt_CM_Order__c</fullName>
        <label>CM Order</label>
        <referenceTo>ptt_cm_Order__c</referenceTo>
        <relationshipLabel>CM End Users</relationshipLabel>
        <relationshipName>CM_End_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ptt_Company_Name__c</fullName>
        <label>Company Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>PT - CM End User</label>
    <nameField>
        <label>End User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM End Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ptt_cm_Order__c.object
<CustomObject>
    <fields>
        <fullName>ptt_Activation_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Activation Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ptt_Activation_Counter__c</fullName>
        <label>Activation Counter</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ptt_Active_CustomPackages__c</fullName>
        <label>Active Packages</label>
        <summaryFilterItems>
            <field>CM_Selected_Package__c.ptt_IsActive__c</field>
            <operation>equals</operation>
            <value>true</value>
        </summaryFilterItems>
        <summaryForeignKey>CM_Selected_Package__c.ptt_CM_Order__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ptt_CD_Serial_Number__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CD Serial Number</label>
        <referenceTo>CM_CD_Serial_Number__c</referenceTo>
        <relationshipLabel>CM Orders</relationshipLabel>
        <relationshipName>CM_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_End_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to End user</description>
        <label>End User</label>
        <referenceTo>ptt_cm_End_User__c</referenceTo>
        <relationshipLabel>CM Orders</relationshipLabel>
        <relationshipName>CM_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ptt_ProductID__c</fullName>
        <label>ProductID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ptt_Sales_Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Channel</label>
        <referenceTo>ptt_cm_Sales_Channel__c</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_System__c</fullName>
        <label>System</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Calimaster</fullName>
                </value>
                <value>
                    <fullName>VIBGUARD Viewer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ptt_Variant__c</fullName>
        <label>Variant</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ptt_System__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Server</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PT - CM Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ptt_cm_Sales_Channel__c.object
<CustomObject>
    <description>Sales Channel for CM</description>
    <label>PT - CM Sales Channel</label>
    <nameField>
        <label>Sales Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Sales Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/as_SalesChannelDetailsController.cls
public class as_SalesChannelDetailsController {
    
    /****************************************/
    /***** Controller global variables ******/
    /****************************************/
    // Constants
    Static final Integer ACTIVATION_COUNTER_LIMIT = 3;
    
    // Variables
    private ptt_cm_Sales_Channel__c salesChannelObj; //Sales Channel Object
    ApexPages.StandardController stdController; // Standard controller
    String scId = ApexPages.currentPage().getParameters().get('Id');
    private String first_picklist_option = 'All'; //First item of System picklist    
    List<ptt_cm_Order__c> ordersList; // List of CM orders for table Orders List
    
    // Automatic get set
    public Id orderIdToDelete {get; set;}
    public String systemSelecedOption {get; set;} //picklist "System"
    public String orderNameToDelete {get; set;}
    public String isCreateLicenseDisabled {get; set;}
    public String activationCode {get; set;}

    /****************************************/
    /**** Custom controller constructor *****/
    /****************************************/
    public as_SalesChannelDetailsController(ApexPages.StandardController controller) {
        this.stdController = controller;
        // Return the record that is currently in context, based on the id parameter in the Visualforce page URL.
        this.salesChannelObj = (ptt_cm_Sales_Channel__c)stdController.getRecord(); 
        activationCode = '';
    }   
    
    /************** Getters *****************/
    /*** Passing values to VS Page fields ***/
    /****************************************/
    
    // Generate System picklist options values
    public List<SelectOption> getSystemOptions() {   
        final sObject picklist_object = new ptt_cm_Order__c();
        return getPickValues(picklist_object, 'ptt_System__c', first_picklist_option);
    }

    // Generate initial values for Order List
    public List<ptt_cm_Order__c> getOrdersTableContent() {
        if (activationCode.length() == 0 && systemSelecedOption == null) {
            queryAllSCOrders(); // call the function which set up global variable value to all realted records
        }
        return this.ordersList;   
    }

    /************** Buttons *****************/
    /** Actions invoked by custom buttons ***/
    /****************************************/

    /* Save */
    public PageReference scSave() {
        stdController.save(); // Standard save action
        PageReference pr = Page.asSalesChannelOverview;
        pr.setRedirect(true);
        return pr;
    }

    /* Back */
    public PageReference scBack() {
        PageReference pr = Page.asSalesChannelOverview;
        pr.getParameters().put('nooverride','1');
        pr.setRedirect(true);
        return pr;
    }

    /* New Order */    
    public PageReference doNewOrder() {
        PageReference pr = page.asNewOrder;
        pr.getParameters().put('scId', SalesChannelObj.Id);
        pr.setRedirect(true);
        return pr;
    }
    
    /* Filter */
    public PageReference doFilterOrders() {
        String queryText = '';
        if (activationCode.length() > 0) {
            queryText = String.escapeSingleQuotes(activationCode.replace('*','%'));
        }
        // When System is All and no Activation code entered
        if (systemSelecedOption.equals(first_picklist_option) && activationCode.length() == 0) {
            queryAllSCOrders();
        }
        // When System is All and Activation code is entered
        else if (systemSelecedOption.equals(first_picklist_option) && activationCode.length() > 0) {
        ordersList = [SELECT Id, name, ptt_System__c, ptt_Variant__c, ptt_Activation_Code__c, ptt_Is_Active__c, ptt_Sales_Channel__c,
                     ptt_CD_Serial_Number__r.Name, ptt_Activation_Counter__c, ptt_ProductID__c, ptt_Active_CustomPackages__c, ptt_End_User__r.ptt_Company_Name__c
                    FROM ptt_cm_Order__c 
                    WHERE ptt_Sales_Channel__c = :scId 
                    AND ptt_Activation_Code__c LIKE :queryText
                    ORDER BY Name ASC ];
        } 
        // When System is not All and Activation code is entered
        else if (!systemSelecedOption.equals(first_picklist_option) && activationCode.length() > 0) {
        ordersList = [SELECT Id, name, ptt_System__c, ptt_Variant__c, ptt_Activation_Code__c, ptt_Is_Active__c, ptt_Sales_Channel__c,
                     ptt_CD_Serial_Number__r.Name, ptt_Activation_Counter__c, ptt_ProductID__c, ptt_Active_CustomPackages__c, ptt_End_User__r.ptt_Company_Name__c
                    FROM ptt_cm_Order__c 
                    WHERE ptt_Sales_Channel__c = :scId 
                    AND ptt_System__c = :systemSelecedOption 
                    AND ptt_Activation_Code__c LIKE :queryText
                    ORDER BY Name ASC ];
        } 
        // When System is not All and no Activation code entered
        else if (!systemSelecedOption.equals(first_picklist_option) && activationCode.length() == 0) {
        ordersList = [SELECT Id, name, ptt_System__c, ptt_Variant__c, ptt_Activation_Code__c, ptt_Is_Active__c, ptt_Sales_Channel__c,
                     ptt_CD_Serial_Number__r.Name, ptt_Activation_Counter__c, ptt_ProductID__c, ptt_Active_CustomPackages__c, ptt_End_User__r.ptt_Company_Name__c
                    FROM ptt_cm_Order__c 
                    WHERE ptt_Sales_Channel__c = :scId 
                    AND ptt_System__c = :systemSelecedOption 
                    ORDER BY Name ASC ];
        } 
        return null;
        
    }
    
    /* All */
    public PageReference doShowAllOrders() {
        activationCode = ''; // reset field to empty string
        systemSelecedOption = first_picklist_option; // Set picklist to first value
        queryAllSCOrders (); // display all SC related records
        return null;
    }
    
    /*********** Command links **************/
    /*** Actions invoked by comand links ****/
    /****************************************/
    
    /* Edit order */
    public PageReference doOrderEdit() {
        PageReference pr = Page.asEditOrder;
        pr.setRedirect(true);
        return pr;
    }
    
    /* Delete order */
    public PageReference doDeleteOrder() {
        // Check if order has packages
        Integer hasPackages = [SELECT Count() FROM CM_Selected_Package__c WHERE ptt_CM_Order__c = :orderIdToDelete];
        if (hasPackages > 0) {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO, 'Order ' + orderNameToDelete + ' cannot be removed because it contains packages.'));
        } else {
            Database.Delete (orderIdToDelete);
            queryAllSCOrders();
        }
        return null;
    }
    

    /****************************************/
    /**** Class specific helper functions ***/
    /****************************************/
     
    public void queryAllSCOrders () {
        ordersList = [SELECT Id, Name, ptt_System__c, ptt_Variant__c, ptt_Activation_Code__c, ptt_Is_Active__c, ptt_Sales_Channel__c,
                      ptt_CD_Serial_Number__r.Name, ptt_Activation_Counter__c, ptt_ProductID__c, ptt_Active_CustomPackages__c, ptt_End_User__r.ptt_Company_Name__c
                      FROM ptt_cm_Order__c 
                      WHERE ptt_Sales_Channel__c =:scId
                      ORDER BY Name ASC];
    }
      
    /**
    * Read picklist values from existig pciklist and return them as options for VS apex:selectOptions
    * @param object_name    object which contains picklist
    * @param field_name     API name of picklist field
    * @param first_val      String like "All" which is a first value
    * @return               Retunrs list of options for VS picklist
    * @see http://www.interactiveties.com/b_describe_picklist.php
    */
    public List<selectOption> getPickValues(sObject object_name, String field_name, String first_val) {
        List<selectOption> options = new List<selectOption>(); //new list for holding all of the picklist options
        if (first_val != null) { //if there is a first value being provided
            options.add(new selectOption(first_val, first_val)); //add the first option
        }
        Schema.sObjectType sobject_type = object_name.getSObjectType(); //grab the sobject that was passed   
        Schema.DescribeSObjectResult sobject_describe = sobject_type.getDescribe(); //describe the sobject
        Map<String, Schema.SObjectField> field_map = sobject_describe.fields.getMap(); //get a map of fields for the passed sobject
        List<Schema.PicklistEntry> pick_list_values = field_map.get(field_name).getDescribe().getPickListValues(); //grab the list of picklist values for the passed field on the sobject
        for (Schema.PicklistEntry a : pick_list_values) { //for all values in the picklist list
           options.add(new selectOption(a.getLabel(), a.getValue())); //add the value and label to our final list
        }
        return options; //return the List
   }
   
  
    
}