objects/CM_CD_Serial_Number__c.object
<CustomObject>
    <description>Contains CD Serial numbers and Activation Codes pairs</description>
    <label>PT - CM CD Serial Number</label>
    <nameField>
        <label>CD Serial No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM CD Serial Numbers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CM_Custom_Package__c.object
<CustomObject>
    <description>This object hold complete packages created by users from features.</description>
    <label>PT - CM Custom Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Custom Packages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ptt_cm_End_User__c.object
<CustomObject>
    <fields>
        <fullName>ptt_CM_Order__c</fullName>
        <label>CM Order</label>
        <referenceTo>ptt_cm_Order__c</referenceTo>
        <relationshipLabel>CM End Users</relationshipLabel>
        <relationshipName>CM_End_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>PT - CM End User</label>
    <nameField>
        <label>End User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM End Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ptt_cm_Order__c.object
<CustomObject>
    <fields>
        <fullName>ptt_Activation_Counter__c</fullName>
        <label>Activation Counter</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ptt_CD_Serial_Number__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CD Serial Number</label>
        <referenceTo>CM_CD_Serial_Number__c</referenceTo>
        <relationshipLabel>CM Orders</relationshipLabel>
        <relationshipName>CM_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_End_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to End user</description>
        <label>End User</label>
        <referenceTo>ptt_cm_End_User__c</referenceTo>
        <relationshipLabel>CM Orders</relationshipLabel>
        <relationshipName>CM_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ptt_ProductID__c</fullName>
        <label>ProductID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ptt_Sales_Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Channel</label>
        <referenceTo>ptt_cm_Sales_Channel__c</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PT - CM Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ptt_cm_Sales_Channel__c.object
<CustomObject>
    <description>Sales Channel for CM</description>
    <label>PT - CM Sales Channel</label>
    <nameField>
        <label>Sales Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Sales Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/as_editOrderController_Test.cls
@isTest
public with sharing class as_editOrderController_Test {

 	public static testMethod void test_editOrderControllerController() {
        // Set page in context
        PageReference pageRef = Page.asCreateLicense;
        Test.setCurrentPage(pageRef);
     	
     	// Create Sales Channel
		ptt_cm_Sales_Channel__c sc = as_TestHelper.createCmSalesChannel(TRUE);
		
		// Crete end user data
		ptt_cm_End_User__c eud = as_TestHelper.createCmEndUserData(TRUE);
		
		// Insert CD Serial number
		CM_CD_Serial_Number__c csn = as_TestHelper.createCmCDSerialNumber(TRUE);
		
		// Insert order
		ptt_cm_Order__c cmo = as_TestHelper.createCmOrder(FALSE);
		cmo.ptt_Sales_Channel__c = sc.Id;
		cmo.ptt_End_User__c = eud.Id;
		cmo.ptt_CD_Serial_Number__c = csn.Id;
		cmo.ptt_ProductID__c = '123456789';
		cmo.ptt_Is_Active__c = TRUE;
		cmo.ptt_Activation_Counter__c = 0;
		insert cmo;
     	
     	// Add URL parameters
		ApexPages.currentPage().getParameters().put('Id', cmo.Id); 
    	
     
    	// Set Controller in context  
		as_editOrderController controllerExt = new as_editOrderController (new ApexPages.StandardController(cmo) );
	   
     	// Save button
     	System.assertEquals(null, controllerExt.orderSave() );
     	
     	// Back button
     	System.assertEquals('/apex/assaleschanneldetails?Id=' + sc.Id, controllerExt.orderEditBack().getUrl() );
     	
        // Create License button
        System.assertEquals('/apex/ascreatelicense?orderId=' + cmo.Id, controllerExt.doCreateLicense().getUrl() );
     	
        // Reset button
        System.assertEquals('/apex/asresetcounter?orderId=' + cmo.Id, controllerExt.doResetCounter().getUrl() );
     	
        // Details button
       // System.assertEquals('/apex/aseditordernumbers?orderId=' + cmo.Id, controllerExt.doEditOrderNumbers().getUrl() );
     	
     	// Add button
     //	System.assertEquals('/apex/asaddcustompackage?orderId=' + cmo.Id, controllerExt.doAddPackage().getUrl() );
     
        // Del link
        // Create custom package
		CM_Custom_Package__c cp = as_TestHelper.createCmCustomPackage(TRUE);
        controllerExt.selectedPackageId = cp.Id;
        System.assertEquals(null, controllerExt.doDeletePackage() );
     
        
 	}     
        
}