objects/CM_CD_Serial_Number__c.object
<CustomObject>
    <description>Contains CD Serial numbers and Activation Codes pairs</description>
    <fields>
        <fullName>ptt_Activation_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Activation code in format 1234-1234-1234-1234</description>
        <label>Activation Code</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>PT - CM CD Serial Number</label>
    <nameField>
        <label>CD Serial No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM CD Serial Numbers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ptt_cm_Order__c.object
<CustomObject>
    <fields>
        <fullName>ptt_Activation_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Activation Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ptt_CD_Serial_Number__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CD Serial Number</label>
        <referenceTo>CM_CD_Serial_Number__c</referenceTo>
        <relationshipLabel>CM Orders</relationshipLabel>
        <relationshipName>CM_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ptt_Sales_Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Channel</label>
        <referenceTo>ptt_cm_Sales_Channel__c</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_System__c</fullName>
        <label>System</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Calimaster</fullName>
                </value>
                <value>
                    <fullName>VIBGUARD Viewer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ptt_Variant__c</fullName>
        <label>Variant</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ptt_System__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Server</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PT - CM Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ptt_cm_Sales_Channel__c.object
<CustomObject>
    <description>Sales Channel for CM</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CM Sales Channels</relationshipLabel>
        <relationshipName>Sales_Channels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_Business_Unit__c</fullName>
        <formula>Account_Name__r.sf42_Business_Unit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ptt_remote_access__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Remote access</label>
        <type>Checkbox</type>
    </fields>
    <label>PT - CM Sales Channel</label>
    <nameField>
        <label>Sales Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Sales Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/as_SalesChannelOverviewController.cls
public with sharing class as_SalesChannelOverviewController {

    /****************************************/
    /***** Controller global variables ******/
    /****************************************/ 
    ApexPages.StandardController stdController;
    List<ptt_cm_Sales_Channel__c> filteredList;
    static List<ptt_cm_Order__c> filteredCmOrdersList = new List<ptt_cm_Order__c>();
    public Boolean orderTableRendered {get; set;}
    public Boolean sChannelTableRendered {get; set;}

    // Automatic get set
    public String searchName {get; set;}
    public String activationCode {get; set;}
    
    /****************************************/
    /**** Custom controller constructor *****/
    /****************************************/
    
    public as_SalesChannelOverviewController(ApexPages.StandardController stdController) {
        this.stdController = stdController;
        searchName = '';
        activationCode = '';
        orderTableRendered = FALSE;
        SChannelTableRendered =  TRUE;
    }

    /************** Getters *****************/
    /*** Passing values to VS Page fields ***/
    /****************************************/

    /* Sales Channell table */
    public List<ptt_cm_Sales_Channel__c> getScTableContent () {
        if (searchName.length() == 0 && activationCode.length() == 0) {
            filteredList = [SELECT id, Name, ptt_Business_Unit__c, ptt_remote_access__c, Account_Name__r.Name  
                            FROM ptt_cm_Sales_Channel__c 
                            ORDER BY Name ASC];
        }
        return filteredList;
    }
    /* Orders table */
    public List<ptt_cm_Order__c> getOrdersTableContent () {
 			return filteredCmOrdersList;
    }
    
    /************** Buttons *****************/
    /** Actions invoked by custom buttons ***/
    /****************************************/
    
    /* New Sales Channel */
    public PageReference doCreateNewSalesChannel() {       
        PageReference pr = Page.asNewSalesChannel;
        pr.setRedirect(true);
        return pr;
    }
     
    /* Filter SCName */   
    public PageReference doFilter() {
    	// Escape single quotes to prevent SQL Injection
    	activationCode = '';
        searchName = String.escapeSingleQuotes(searchName);
        activationCode = String.escapeSingleQuotes(activationCode);
        
        if (searchName != '' || searchName != null) {   
	        String queryText = searchName.replace('*','%');
	        filteredList = [SELECT id, Name, ptt_Business_Unit__c, ptt_remote_access__c, Account_Name__r.Name 
	                        FROM ptt_cm_Sales_Channel__c 
	                        WHERE Name LIKE :queryText ORDER BY Name ASC];
	    
	        orderTableRendered = FALSE;
	        SChannelTableRendered = TRUE;
        }
        return null;
    }
    
    /* All SCNames */
    public PageReference doShowAll() {
        searchName = '';
        activationCode = '';
        filteredList = [SELECT id, Name, ptt_Business_Unit__c, ptt_remote_access__c, Account_Name__r.Name 
                        FROM ptt_cm_Sales_Channel__c 
                        ORDER BY Name ASC];
       
        orderTableRendered = FALSE;
        SChannelTableRendered = TRUE;
        return null;
    }
    
    /* Filter Activation Codes */  
    public PageReference doFilterActCode() {
    	searchName = '';
    	// Escape single quotes to prevent SQL Injection
    	searchName = String.escapeSingleQuotes(searchName);
        activationCode = String.escapeSingleQuotes(activationCode);

        if (activationCode != '') {
        	String acodeQuery = activationCode.replace('*','%');

        	// Search for order with given Activation code
        	filteredCmOrdersList.addAll(
        		[SELECT Id, name, ptt_System__c, ptt_Variant__c, ptt_Activation_Code__c, ptt_Sales_Channel__c, ptt_Sales_Channel__r.Name, ptt_CD_Serial_Number__r.Name, ptt_Is_Active__c
                 FROM ptt_cm_Order__c WHERE ptt_Activation_Code__c LIKE :acodeQuery]);

			orderTableRendered = TRUE;
			SChannelTableRendered = FALSE;
        } else {
			doShowAllActCodes();
        }
        return null;
    }
    
    /* All Activation Codes */
    public PageReference doShowAllActCodes() {
        searchName = '';
        activationCode = '';

        filteredCmOrdersList.addAll(
        		[SELECT Id, name, ptt_System__c, ptt_Variant__c, ptt_Activation_Code__c, ptt_Sales_Channel__c, ptt_Sales_Channel__r.Name, ptt_CD_Serial_Number__r.Name, ptt_Is_Active__c
                 FROM ptt_cm_Order__c ]);
        	                     
        orderTableRendered = TRUE;
        SChannelTableRendered = FALSE;
        return null;
    }

}