objects/CM_Custom_Package__c.object
<CustomObject>
    <description>This object hold complete packages created by users from features.</description>
    <fields>
        <fullName>ptt_IdCode__c</fullName>
        <description>Format VIB x.yyy</description>
        <inlineHelpText>Format VIB x.yyy</inlineHelpText>
        <label>Material item number</label>
        <length>13</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>PT - CM Custom Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Custom Packages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/as_NewCustomPackage_Controller.cls
public with sharing class as_NewCustomPackage_Controller {
    
    /****************************************/
    /***** Controller global variables ******/
    /****************************************/

    private CM_Custom_Package__c custPackageObj; //Object for standard controller
    ApexPages.StandardController stdController; // Standard controller
    
    // Variables with default get set methods
    
    /****************************************/
    /**** Custom controller constructor *****/
    /****************************************/
    public as_NewCustomPackage_Controller(ApexPages.StandardController controller) {
        this.stdController = controller;
        this.custPackageObj = (CM_Custom_Package__c)stdController.getRecord();
    }

    /*************** Buttons ****************/
    /*** Actions invoked by custom buttons **/
    /****************************************/

    public PageReference doSavePackage() {
        if (isMaterialItemNumerValid() == TRUE) {       
            try{
                insert custPackageObj;
            }
            catch (DmlException e) {
            	if ( e.getMessage().contains('DUPLICATE_VALUE') ) {
            		custPackageObj.ptt_IdCode__c.addError('Number is already used in another package.');
            		return null;
            	} else {
                	ApexPages.addMessages(e);
                	return null;
            	}
            }
            // catch duplicate value error and display it under filed
            
            PageReference pr = Page.asEditCustomPackage;
            pr.getParameters().put('Id', custPackageObj.Id);
            pr.setRedirect(true);
            return pr;         
        } else {
            return null;
        }       
    }
    
    /****************************************/
    /*** Class specific helper functions ****/
    /****************************************/ 
    
    boolean isMaterialItemNumerValid() {
        // It is now implemented as Validation rule on "CM Custom Package" object.
        return TRUE;
    }
    
}