objects/CM_Custom_Package__c.object
<CustomObject>
    <description>This object hold complete packages created by users from features.</description>
    <fields>
        <fullName>ptt_Index__c</fullName>
        <label>Index</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PT - CM Custom Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Custom Packages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CM_Selected_Package__c.object
<CustomObject>
    <description>This is a link object which links Orders and Custom Packages</description>
    <fields>
        <fullName>ptt_CM_Custom_Package__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Relation to selected Custom Package</description>
        <label>CM Custom Package</label>
        <referenceTo>CM_Custom_Package__c</referenceTo>
        <relationshipName>CM_Selected_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_CM_Order__c</fullName>
        <label>CM Order</label>
        <referenceTo>ptt_cm_Order__c</referenceTo>
        <relationshipName>CM_Selected_Packages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ptt_Index__c</fullName>
        <label>Index</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ptt_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>PT - CM Selected Package</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>CM Selected Packages Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Selected Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ptt_cm_Order__c.object
<CustomObject>
    <label>PT - CM Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/as_AddCustomPackageController_Test.cls
@isTest
public with sharing class as_AddCustomPackageController_Test {
	
	public static testMethod void test_AddCustomPackageController() {
        /* Configure enviroment */
        
        // Prepare database structure 
        ptt_cm_Order__c cmOrder = as_TestHelper.createCmOrder(TRUE);
        CM_Custom_Package__c pkgOne = as_TestHelper.createCmCustomPackage(TRUE);
        CM_Custom_Package__c pkgTwo = as_TestHelper.createCmCustomPackage(TRUE);
        // Connect package with Order
        CM_Selected_Package__c orderPkgLink = new CM_Selected_Package__c();
        orderPkgLink.ptt_CM_Custom_Package__c = pkgOne.Id;
        orderPkgLink.ptt_CM_Order__c = cmOrder.Id;
        orderPkgLink.ptt_Index__c = 1;
        orderPkgLink.ptt_IsActive__c = TRUE;
        insert orderPkgLink;
               
        // Set page in context
        PageReference pageRef = Page.asAddCustomPackage;
        Test.setCurrentPage(pageRef);
        
		// Set url parameters
		ApexPages.currentPage().getParameters().put('OrderId', cmOrder.Id); 
    
    	// Set Controller in context  
		as_AddCustomPackageController controller = new as_AddCustomPackageController ();
	
		/* Start testing */
		
		// Back button
		System.assertEquals('/apex/aseditorder?Id=' + cmOrder.Id, controller.BackToOrder().getUrl() );
		
		// Save button		
		System.assertEquals('/apex/aseditorder?Id=' + cmOrder.Id, controller.SaveSelectedPackages().getUrl() );
		
		
		
	}

}