objects/CM_Custom_Package__c.object
<CustomObject>
    <description>This object hold complete packages created by users from features.</description>
    <fields>
        <fullName>ptt_Variant__c</fullName>
        <description>Specific sub type of system. It is allowed to select more than one as package can fit for more variants.</description>
        <label>Variant</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>ptt_System__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Server</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PT - CM Custom Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Custom Packages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/as_NewCustomPackage_Controller_Test.cls
public with sharing class as_NewCustomPackage_Controller_Test {
	
	public static testMethod void test_as_NewCustomPackage_Controller() {
		/* Configure enviroment */

		// Prepare database structure
		CM_Custom_Package__c cmCustPkg = as_TestHelper.createCmCustomPackage(FALSE);
		
        // Set page in context
        PageReference pageRef = Page.asNewCustomPackage;
        Test.setCurrentPage(pageRef);
        
        // Set url parameters
     
    	// Set Controller in context  
		as_NewCustomPackage_Controller controllerExt = new as_NewCustomPackage_Controller (new ApexPages.StandardController(cmCustPkg) );
		
		/* Start testing */
		
		// Save button	
		System.assert(controllerExt.doSavePackage().getUrl().contains('/apex/aseditcustompackage') );
		
		// Try to save when missing one parameter
		cmCustPkg.ptt_Variant__c = '';
		System.assertEquals(null, controllerExt.doSavePackage());
		
 	}
}