objects/CM_Selected_Package__c.object
<CustomObject>
    <description>This is a link object which links Orders and Custom Packages</description>
    <fields>
        <fullName>ptt_CM_Custom_Package__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Relation to selected Custom Package</description>
        <label>CM Custom Package</label>
        <referenceTo>CM_Custom_Package__c</referenceTo>
        <relationshipName>CM_Selected_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_CM_Order__c</fullName>
        <label>CM Order</label>
        <referenceTo>ptt_cm_Order__c</referenceTo>
        <relationshipName>CM_Selected_Packages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ptt_Index__c</fullName>
        <label>Index</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ptt_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>PT - CM Selected Package</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>CM Selected Packages Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Selected Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/cm_tan_List__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>PT - CM TAN list</label>
</CustomObject>

objects/ptt_cm_End_User__c.object
<CustomObject>
    <fields>
        <fullName>ptt_CM_Order__c</fullName>
        <label>CM Order</label>
        <referenceTo>ptt_cm_Order__c</referenceTo>
        <relationshipLabel>CM End Users</relationshipLabel>
        <relationshipName>CM_End_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ptt_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ptt_Company_Name__c</fullName>
        <label>Company Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ptt_Country2__c</fullName>
        <label>Country2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ptt_CountryISO2__c</fullName>
        <description>Two letters Country Iso code</description>
        <label>Country ISO Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ptt_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ptt_Industry__c</fullName>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Automation</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Cement</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Converting</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Facilities</fullName>
                </value>
                <value>
                    <fullName>Food &amp; Beverage</fullName>
                </value>
                <value>
                    <fullName>Machine Manufacturers</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Marine &amp; Shipping</fullName>
                </value>
                <value>
                    <fullName>Metal</fullName>
                </value>
                <value>
                    <fullName>Mining</fullName>
                </value>
                <value>
                    <fullName>Oil &amp; Gas</fullName>
                </value>
                <value>
                    <fullName>Petro chemical</fullName>
                </value>
                <value>
                    <fullName>Power Generation</fullName>
                </value>
                <value>
                    <fullName>Printing</fullName>
                </value>
                <value>
                    <fullName>Public Sector</fullName>
                </value>
                <value>
                    <fullName>Pulp and Paper</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Wood Industry</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ptt_Industry_subcategory__c</fullName>
        <label>Industry subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ptt_Industry__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Agricultural machinery</fullName>
                </value>
                <value>
                    <fullName>Aircraft, aircraft parts</fullName>
                </value>
                <value>
                    <fullName>Air Force</fullName>
                </value>
                <value>
                    <fullName>Army</fullName>
                </value>
                <value>
                    <fullName>Banking</fullName>
                </value>
                <value>
                    <fullName>Biogas</fullName>
                </value>
                <value>
                    <fullName>Blowers, fans</fullName>
                </value>
                <value>
                    <fullName>Bottling plants</fullName>
                </value>
                <value>
                    <fullName>Breweries</fullName>
                </value>
                <value>
                    <fullName>Cardboard</fullName>
                </value>
                <value>
                    <fullName>Certification Bodies</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Coal</fullName>
                </value>
                <value>
                    <fullName>Colleges</fullName>
                </value>
                <value>
                    <fullName>Compressors</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Conveyors</fullName>
                </value>
                <value>
                    <fullName>Corrugated</fullName>
                </value>
                <value>
                    <fullName>Couplings</fullName>
                </value>
                <value>
                    <fullName>Cranes</fullName>
                </value>
                <value>
                    <fullName>Desalination plant</fullName>
                </value>
                <value>
                    <fullName>Diesel engines</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Environmental</fullName>
                </value>
                <value>
                    <fullName>Exploration - Offshore</fullName>
                </value>
                <value>
                    <fullName>Exploration - Onshore</fullName>
                </value>
                <value>
                    <fullName>Extruders</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ptt_State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ptt_Street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ptt_Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PT - CM End User</label>
    <nameField>
        <label>End User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM End Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ptt_cm_Order__c.object
<CustomObject>
    <fields>
        <fullName>ptt_Activation_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Activation Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ptt_Activation_Counter__c</fullName>
        <label>Activation Counter</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ptt_End_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to End user</description>
        <label>End User</label>
        <referenceTo>ptt_cm_End_User__c</referenceTo>
        <relationshipLabel>CM Orders</relationshipLabel>
        <relationshipName>CM_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ptt_ProductID__c</fullName>
        <label>ProductID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ptt_Sales_Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Channel</label>
        <referenceTo>ptt_cm_Sales_Channel__c</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PT - CM Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ptt_cm_Sales_Channel__c.object
<CustomObject>
    <description>Sales Channel for CM</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CM Sales Channels</relationshipLabel>
        <relationshipName>Sales_Channels</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PT - CM Sales Channel</label>
    <nameField>
        <label>Sales Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Sales Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/as_CreateLicenseController.cls
public class as_CreateLicenseController {
    
    /****************************************/
    /***** Controller global variables ******/
    /****************************************/
    
    // Constants
    //static final String BASE_URL = 'https://smtp.pruftechnik-cm.com:8443/com.pruftechnik.rcm.server.keygenerator';
    static final String BASE_URL = 'https://smtp.pruftechnik-cm.com:8444/com.pruftechnik.rcm.server.keygenerator';
    
    static final String AUTH_PATH = '/authenticate';
    static final String LICENSE_PATH = '/license-generator';

    static final String AUTH_SUCCESS_MESSAGE = 'message_key_values'; // span ID name which contains message
    static final String AUTH_SUCCESS_MESSAGE_VALUE = 'get a licens'; // string which indicate that we can continue to licese download
    
    // Variables
    
    //static String username = 'activation-server-production';
    //static String password = 'xt8zxfhecit1r4pyyvrygov3';
     
    //static String username = 'activation-server';
    //static String password = 'aqkg1cho68vp5lrzgkensahw';
 
    static String username = 'activation-server-ptsandbox';
    static String password = 'GYGMzQaytvHcSq9Q5pZ7YpRr';   
    
    
    
    private ptt_cm_Order__c cmOrderObject;
    private ptt_cm_End_User__c endUserObject = new ptt_cm_End_User__c();
    private List<CM_Selected_Package__c > activePackagesList = new List<CM_Selected_Package__c >();
    private ptt_cm_Sales_Channel__c salesChannel = new ptt_cm_Sales_Channel__c();
    
    private String orderId = '';
    private String errorMsg = '';
 
    private String authenticateURL = BASE_URL + AUTH_PATH;
    private String authenticateParams = 'user=' + username + '&pwd=' + password; 
    private String licenseURL = '';
    private String licenseParams = '';
   
    private String tan = '', license = '', enduser = '', packages = '';
    private Integer tanindex = 0;
    
    private cm_tan_List__c cmTan2 = new cm_tan_List__c();
    //Map<String,String> cmTan2 = new Map<String,String>();
        
    // Variables with default get set methods
    public String CommentText { get; set; }
    public String orderName { get; set; }
    public boolean hasAnyStoppers { get; set; } 
    public Id attDlID { get; set; }
    public String attDlName { get; set; } 
    
    /****************************************/
    /**** Custom controller constructor *****/
    /****************************************/
    public as_CreateLicenseController() {
       
        // Extract id from parameter
        orderId = ApexPages.currentPage().getParameters().get('orderid');
        if (orderId != null && orderId != '') {
            hasAnyStoppers = FALSE;
            
            cmOrderObject = [SELECT Id, Name, ptt_Is_Active__c, ptt_Activation_Code__c, ptt_End_User__c, ptt_Activation_Counter__c, ptt_Sales_Channel__c, ptt_ProductID__c, ptt_Sales_Channel__r.Account_Name__c
                             FROM ptt_cm_Order__c 
                             WHERE Id = :orderId];
                             
            // Get Active packages for this object
            activePackagesList = [SELECT Id, ptt_Index__c, ptt_IsActive__c, ptt_CM_Custom_Package__c 
                                  FROM CM_Selected_Package__c 
                                  WHERE ptt_CM_Order__c = :orderId AND ptt_IsActive__c = TRUE ];
           
            // Pass order name to page.        
            orderName = cmOrderObject.name;
    
            // Check if order is active and did not reached maximum activation limit
            if (cmOrderObject.ptt_Is_Active__c == FALSE) {
                hasAnyStoppers = TRUE;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO, 'Order is not active, you can not create license.'));
            }
            else if (cmOrderObject.ptt_Activation_Counter__c > 2) {
                hasAnyStoppers = TRUE;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO, 'Order reached maximum activation limit'));
            }
            else if (cmOrderObject.ptt_Activation_Code__c == null || cmOrderObject.ptt_End_User__c == null) {
                hasAnyStoppers = TRUE;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO, 'Order is missing important informations.'));
            } 
            else if (activePackagesList.size() < 1) {
                hasAnyStoppers = TRUE;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO, 'Order do not have any active packagaes'));
            }
            else { // Load data which are needed to create license
                   
                // Get end user record which is connected to this order    
                endUserObject = [SELECT Id, Name, ptt_Company_Name__c, ptt_City__c, ptt_CM_Order__c, ptt_Country2__c, ptt_CountryISO2__c, ptt_Email__c, ptt_Industry__c, ptt_Industry_subcategory__c, ptt_State__c, ptt_Street__c, ptt_Zip_Postal_Code__c 
                                 FROM ptt_cm_End_User__c 
                                 WHERE Id = :cmOrderObject.ptt_End_User__c];   
                                 
                salesChannel = [SELECT id, Account_Name__c 
                                FROM ptt_cm_Sales_Channel__c 
                                WHERE Id =: cmOrderObject.ptt_Sales_Channel__c];        
            }
            
            // Create Packages parameter value
            try {
                String packages = as_licenseGenerator.generatePackagesParameterValue(orderId);
            } catch (as_Exceptions.licGenException ex) { 
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO, ex.getDetails()));
                hasAnyStoppers = TRUE;
            }
        } else {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO, 'Missing OrderId Parameter'));
            hasAnyStoppers = TRUE;
        }
        
    } 
    
    /********** Immediate actions ***********/
    /***** Actions executed on page load ****/
    /****************************************/
    
    /* Get the valid TAN and select it as used */
    public void obtainTan() {
    	this.cmTan2 = as_licenseGenerator.getTransactionTan();
    }
    
    /************** Buttons *****************/
    /** Actions invoked by custom buttons ***/
    /****************************************/
    
    /* Create */
    public PageReference CreateLic() {
    //	try { 
	        if (CommentText == '') {
	            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO, 'Comment field cannot be empty'));
				return null;
	        } else {
	            Http httpConnection = new Http(); // Http connection.
	            String fileURL = ''; 
	            Attachment att = new Attachment(); 
	            Map<String,String> licenseURL = as_licenseGenerator.getLicenseUrl(cmOrderObject, cmTan2.Id); 

	            if (hasAnyStoppers == FALSE &&  packages != null) {
                    httpConnection = as_licenseGenerator.authenticateToKGServer();
System.debug('@@ Before KG error.');
                    att = as_licenseGenerator.askForLicense(httpConnection, cmOrderObject, CommentText );
System.debug('@@ After KG error.');
                    // Redirect to filedownload.
                    fileURL = '/servlet/servlet.FileDownload?file=' + att.Id;
                    attDlId = att.Id;
                    attDlName = att.Name;
                    hasAnyStoppers = TRUE;
		        }
           } 
/*   	  }
		catch (as_Exceptions.licGenException ex) {
	  	ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO, ex.GetMessage() + ' ' + ex.getDetails()));
	  // 	ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO, ex.getDetails()));
  		hasAnyStoppers = TRUE;
  		return null;
    	} 
	*/ 	
        return null;
    }
    
    /*Back */
    public PageReference Back() {
        PageReference pr = Page.asEditOrder;
        pr.getParameters().put('Id', orderId);
        pr.setRedirect(false);
        return pr;
    }
    
    /****************************************/
    /**** Class specific helper functions ***/
    /****************************************/ 
    
    /**
    * Reads error message send by KeyGenerator in http response and
    * transform it to Salesforce apex:pageMessages format
    * @param response - http respnse after server call
    */
    void displayKeyGenError (HttpResponse response) {
        String errorMsg = '';
        String detail = '';
           
        String responseBody = response.getBody();
                                       
        String message_type = ptt_VFControllerHelper.extractValueFromId(responseBody, 'message_type');            
        String message_description = ptt_VFControllerHelper.extractValueFromId(responseBody, 'message_description'); 
        String message_key = ptt_VFControllerHelper.extractValueFromId(responseBody, 'message_key'); 
        String message_key_values = ptt_VFControllerHelper.extractValueFromId(responseBody, 'message_key_values'); 
       
        errorMsg = 'An error occurred: <b>' + message_key + '</b><br/>Message: <b>' + message_description +'</b>';
        // detail = '<br/>BODY: ' + response.getHeaderKeys() + 'Content-Disposition: ' + response.getHeader('Content-Disposition') + ' Content-Type: ' + response.getHeader('Content-Type');
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO, errorMsg, detail));
    }
    
}