objects/Partner_Territory_Criteria_Fields__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Territory Criteria Mandatory Fields For A Specific Business Unit</description>
    <fields>
        <fullName>Account_Criteria_Fields__c</fullName>
        <description>API names of fields separated by a semicolon</description>
        <inlineHelpText>API names of fields separated by a semicolon (as an example for &quot;Billing Country&quot; field you should set &quot;BillingCountry&quot; API name not label &quot;Billing Country&quot;)</inlineHelpText>
        <label>Account Criteria Fields</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Criteria_Fields__c</fullName>
        <description>API names of fields separated by a semicolon</description>
        <inlineHelpText>API names of fields separated by a semicolon (as an example for &quot;Billing Country&quot; field you should set &quot;BillingCountry&quot; API name not label &quot;Billing Country&quot;)</inlineHelpText>
        <label>Lead Criteria Fields</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>PT - Partner Territory Criteria Fields</label>
</CustomObject>

objects/Partner_Territory_Sharing_Common_Fields__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Territory Sharing fields for custom ui page</description>
    <fields>
        <fullName>Field_API_Names__c</fullName>
        <description>API names of fields separated by a semicolon</description>
        <inlineHelpText>API names of fields separated by a semicolon (as an example for &quot;Billing Country&quot; field you should set &quot;BillingCountry&quot; API name not label &quot;Billing Country&quot;)</inlineHelpText>
        <label>Field API Names</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Partner Territory Sharing Common Fields</label>
</CustomObject>

classes/SharingSettingsHelper.cls
public with sharing class SharingSettingsHelper {
	
    public static List<String> getCommonSharingFieldsByObjectName(String objectName) {
        Partner_Territory_Sharing_Common_Fields__c fields = Partner_Territory_Sharing_Common_Fields__c.getInstance(objectName);
        return fields == null ? new List<String>() : fields.Field_API_Names__c.split(';');
    }
    
    public static List<String> getFieldsToProcessByObjectName(String objectName) {
        List<String> fields = getCommonSharingFieldsByObjectName(objectName);
        fields.add(SharingConstants.BUSINESS_UNIT_FIELD_BY_OBJECT.get(objectName));
        return fields;
    }

    public static List<String> getAllFieldsAPINamesByObjectName(String objectName) {

        List<String> fields = new List<String>();
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Map<String, Schema.SObjectField> fieldDetails = schemaMap.get(objectName).getDescribe().fields.getMap();

        fields.addAll(fieldDetails.keySet());
        return fields;
    }

    public static Boolean areMandatoryCriteriaFieldsSet(String businessUnit) {
        Partner_Territory_Criteria_Fields__c criteriaFields = Partner_Territory_Criteria_Fields__c.getInstance(businessUnit);
        return criteriaFields != null;
    }

    public static Map<String, List<String>> getMandatoryCriteriaFields(String businessUnit) {

        Map<String, List<String>> fields = new Map<String, List<String>>();
        Partner_Territory_Criteria_Fields__c criteriaFields = Partner_Territory_Criteria_Fields__c.getInstance(businessUnit);

        if (criteriaFields != null) {
            fields.put(SharingConstants.ACCOUNT_CRITERIA, criteriaFields.Account_Criteria_Fields__c.split(';'));
            fields.put(SharingConstants.LEAD_CRITERIA, criteriaFields.Lead_Criteria_Fields__c.split(';'));
        }
        return fields;
    }
}