objects/ptt_cm_Order__c.object
<CustomObject>
    <fields>
        <fullName>ptt_Order_numbers__c</fullName>
        <label>Order numbers</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ptt_Sales_Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Channel</label>
        <referenceTo>ptt_cm_Sales_Channel__c</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PT - CM Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ptt_cm_Sales_Channel__c.object
<CustomObject>
    <description>Sales Channel for CM</description>
    <label>PT - CM Sales Channel</label>
    <nameField>
        <label>Sales Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Sales Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/as_EditOrderNumbersController_Test.cls
@isTest
public with sharing class as_EditOrderNumbersController_Test {

	public static testMethod void test_as_EditOrderNumbers() {
        // Set page in context
        PageReference pageRef = Page.asEditOrderNumbers;
        Test.setCurrentPage(pageRef);
     
     	// Create Sales Channel
		ptt_cm_Sales_Channel__c sc = as_TestHelper.createCmSalesChannel(TRUE);
		
		// Insert order
		ptt_cm_Order__c cmo1 = as_TestHelper.createCmOrder(FALSE);
		cmo1.ptt_Sales_Channel__c = sc.Id;
		cmo1.ptt_Order_numbers__c = '123;345;';
		insert cmo1;
		
		ApexPages.currentPage().getParameters().put('orderId', cmo1.Id); 
    	
    	// Set Controller in context  
		as_EditOrderNumbersController controller = new as_EditOrderNumbersController();
	
		/* Start testing */

		// Back button
		System.assertEquals('/apex/aseditorder?Id=' + cmo1.id, controller.onBack().getUrl() );
		
		// Delete order number
		controller.orderNumbersValues.add('aaa');
		controller.orderNumbersValues.add('bbb');
		controller.selectedOnValues.add('aaa');
		System.assertEquals(null, controller.doDeleteON() );
		
		// Add order number
		controller.addONValue = '123';
		System.assertEquals(null, controller.doAddON() );
		
		// Add order number
		controller.addONValue = '12;3';
		System.assertEquals(null, controller.doAddON() );
		
		// Save button
		System.assertEquals('/apex/aseditorder?Id=' + cmo1.id, controller.onSave().getUrl() );
		
		
		
		// getter getOrderNumbersOptions()
		System.assert(controller.getOrderNumbersOptions().size() != null );
	}
}