objects/ptt_cm_Order__c.object
<CustomObject>
    <fields>
        <fullName>ptt_Sales_Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Channel</label>
        <referenceTo>ptt_cm_Sales_Channel__c</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PT - CM Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ptt_cm_Sales_Channel__c.object
<CustomObject>
    <description>Sales Channel for CM</description>
    <label>PT - CM Sales Channel</label>
    <nameField>
        <label>Sales Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Sales Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/as_DeleteSalesChannelController_Test.cls
@isTest
public with sharing class as_DeleteSalesChannelController_Test {
	
	 public static testMethod void test_as_NewSalesChannelController() {
        // Set page in context
        PageReference pageRef = Page.asDeleteSalesChannel;
        Test.setCurrentPage(pageRef);
     
     	// Create Sales Channel
		ptt_cm_Sales_Channel__c sc = as_TestHelper.createCmSalesChannel(TRUE);
		
		// Insert order
		ptt_cm_Order__c cmo1 = as_TestHelper.createCmOrder(FALSE);
		cmo1.ptt_Sales_Channel__c = sc.Id;
		insert cmo1;
    	
    	// Set Controller in context  
		as_DeleteSalesChannelController controllerExt = new as_DeleteSalesChannelController(new ApexPages.StandardController(sc));
	
		/* Start testing */

		
		// Add parameters to page URL - page is expecting Id 
        ApexPages.currentPage().getParameters().put('Id', sc.Id);
        
        // Back button
		System.assertEquals('/apex/assaleschanneloverview', controllerExt.doCancel().getUrl() );		
		
		
		// Try to delete sales channel with orders
		System.assertEquals(null, controllerExt.deleteRecord() );
		
		// Check if delete is disabled
		System.assertEquals('true', controllerExt.getdelDisabled() );
		
		// Delete order
		delete cmo1;
		
		// Try to delete SalesChannel
		System.assertEquals('/apex/assaleschanneloverview', controllerExt.deleteRecord().getUrl() );	
	 }

}