objects/ptt_cm_Order__c.object
<CustomObject>
    <fields>
        <fullName>ptt_Activation_Counter__c</fullName>
        <label>Activation Counter</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ptt_Sales_Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Channel</label>
        <referenceTo>ptt_cm_Sales_Channel__c</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PT - CM Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ptt_cm_Sales_Channel__c.object
<CustomObject>
    <description>Sales Channel for CM</description>
    <label>PT - CM Sales Channel</label>
    <nameField>
        <label>Sales Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Sales Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/as_ResetActivationCounter_Test.cls
@isTest
public with sharing class as_ResetActivationCounter_Test {
	
	public static testMethod void test_as_NewSalesChannelController() {
        // Set page in context
        PageReference pageRef = Page.asDeleteSalesChannel;
        Test.setCurrentPage(pageRef);
     
     	// Create Sales Channel
		ptt_cm_Sales_Channel__c sc = as_TestHelper.createCmSalesChannel(TRUE);
		
		// Insert order
		ptt_cm_Order__c cmo1 = as_TestHelper.createCmOrder(FALSE);
		cmo1.ptt_Sales_Channel__c = sc.Id;
		cmo1.ptt_Activation_Counter__c = 2;
		insert cmo1;
		
		//Put URL parameters
		ApexPages.currentPage().getParameters().put('orderid', cmo1.Id); 
    	
    	// Set Controller in context  
		as_ResetActivationCounter controller = new as_ResetActivationCounter();
	
		/* Start testing */
		
		// Back button
		System.assertEquals('/apex/aseditorder?Id=' + cmo1.Id, controller.Back().getUrl() );
		
		// Reset without comment
		//controller.doReset();
		// System.assert(ApexPages.hasMessages() == TRUE  );
		
		// Reset with comment
		controller.CommentText = 'This is a reset comment';
		System.assertEquals('/apex/aseditorder?Id=' + cmo1.Id, controller.doReset().getUrl() );
	}
	

}