objects/ptt_cm_End_User__c.object
<CustomObject>
    <fields>
        <fullName>ptt_CM_Order__c</fullName>
        <label>CM Order</label>
        <referenceTo>ptt_cm_Order__c</referenceTo>
        <relationshipLabel>CM End Users</relationshipLabel>
        <relationshipName>CM_End_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>PT - CM End User</label>
    <nameField>
        <label>End User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM End Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ptt_cm_Order__c.object
<CustomObject>
    <fields>
        <fullName>ptt_Activation_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Activation Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ptt_Activation_Counter__c</fullName>
        <label>Activation Counter</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ptt_CD_Serial_Number__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CD Serial Number</label>
        <referenceTo>CM_CD_Serial_Number__c</referenceTo>
        <relationshipLabel>CM Orders</relationshipLabel>
        <relationshipName>CM_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_End_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to End user</description>
        <label>End User</label>
        <referenceTo>ptt_cm_End_User__c</referenceTo>
        <relationshipLabel>CM Orders</relationshipLabel>
        <relationshipName>CM_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_Sales_Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Channel</label>
        <referenceTo>ptt_cm_Sales_Channel__c</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ptt_System__c</fullName>
        <label>System</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Calimaster</fullName>
                </value>
                <value>
                    <fullName>VIBGUARD Viewer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ptt_Variant__c</fullName>
        <label>Variant</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ptt_System__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Server</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PT - CM Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/as_newOrderController.cls
public with sharing class as_newOrderController {

    /****************************************/
    /***** Controller global variables ******/
    /****************************************/
    private ptt_cm_Order__c cmOrderObj; //cm Order Object  
    private ptt_cm_End_User__c cmEndUser = new ptt_cm_End_User__c();
   // ApexPages.StandardController stdController; // Standard controller
    String scId = ApexPages.currentPage().getParameters().get('scId');
    List<ptt_cm_Order__c> allOrders = new List<ptt_cm_Order__c>();
    
    // Automatic get set
    
    /****************************************/
    /**** Custom controller constructor *****/
    /****************************************/
    public as_newOrderController(ApexPages.StandardController stdController) {
        if (scId == '' || scId == null) {
        	String errorMsg = 'No SalesChannel Id provided.';
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING, errorMsg));
        } else {
	     //   this.stdController = controller;
	        cmOrderObj = (ptt_cm_Order__c)stdController.getRecord(); 
	        cmOrderObj.ptt_Sales_Channel__c = scId;
	        cmOrderObj.ptt_Activation_Counter__c = 0;
    	}
    }
    
    /************** Getters *****************/
    /*** Passing values to VS Page fields ***/
    /****************************************/
    

    /************* Setters *****************/
    /***** Reading values from field *******/
    /***************************************/
    

    /************** Buttons *****************/
    /** Actions invoked by custom buttons ***/
    /****************************************/
    
    // Order section
    
    /* Save */
    public PageReference orderSave() {
        if (cmOrderObj.ptt_System__c == 'Calimaster' && cmOrderObj.ptt_Activation_Code__c == null) {
            cmOrderObj.ptt_Activation_Code__c.addError('Please enter Activation Code manually');
            return null;      
        } else
        if (cmOrderObj.ptt_Variant__c == null) {
            cmOrderObj.ptt_Variant__c.addError('Please select Variant');
            return null;
        } else {
            // Redirection
            PageReference pr = Page.asEditOrder;
            try {
                insert cmOrderObj;
                pr.getParameters().put('Id', cmOrderObj.Id);
                // Create enduser object connected to this order.
                cmEndUser.Name = [SELECT Name FROM ptt_cm_Order__c WHERE Id = :cmOrderObj.Id].Name;
                cmEndUser.ptt_CM_Order__c = cmOrderObj.Id;
                insert cmEndUser;
                cmOrderObj.ptt_End_User__c = cmEndUser.Id;
                update cmOrderObj; 
                return pr;       
            } catch (System.DmlException e) {
                if (e.getMessage().contains('DUPLICATE_VALUE')) {
                	cmOrderObj.ptt_CD_Serial_Number__c.addError('This CD Serial Number is already used, plese check it again.');
                }
                else {
                	cmOrderObj.ptt_CD_Serial_Number__c.addError(e);
                }
                return null;
            }
        }
    }
    
    /* Back */
    public PageReference orderBack() {
        PageReference pr = Page.asSalesChannelDetails;
        pr.getParameters().put('Id', scId);
        return pr;
    }  
    
    /****************************************/
    /**** Class specific helper functions ***/
    /****************************************/

}