objects/Territory_Sharing__c.object
<CustomObject>
    <fields>
        <fullName>Account_Access_Level__c</fullName>
        <label>Account Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Activity_Access_Level__c</fullName>
        <label>Activity Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Access_Level__c</fullName>
        <label>Case Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Access_Level__c</fullName>
        <label>Contact Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Device_Access_Level__c</fullName>
        <label>Device Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group_Id_To_Share_Record_With__c</fullName>
        <description>Role Id of portal user to share found records with</description>
        <label>Group Id To Share With</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Access_Level__c</fullName>
        <label>Lead Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Access_Level__c</fullName>
        <label>Opportunity Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Services_Demos_Access_Level__c</fullName>
        <label>Services Demos Access Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Access_Levels</valueSetName>
        </valueSet>
    </fields>
    <label>PT - Territory Sharing</label>
    <nameField>
        <label>Territory Sharing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Sharing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory_Sharing_Criterion__c.object
<CustomObject>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Value__c</fullName>
        <label>Field Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>equals</fullName>
                    <default>true</default>
                    <label>equals</label>
                </value>
                <value>
                    <fullName>includes</fullName>
                </value>
                <value>
                    <fullName>starts with</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory_Sharing__c</fullName>
        <label>Territory Sharing</label>
        <referenceTo>Territory_Sharing__c</referenceTo>
        <relationshipName>Territory_Sharing_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PT - Territory Sharing Criterion</label>
    <nameField>
        <displayFormat>TSC-{000000}</displayFormat>
        <label>Territory Sharing Criterion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Sharing Criterion</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Access_Levels.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Edit</fullName>
        <default>true</default>
        <label>Read Write</label>
    </customValue>
    <customValue>
        <fullName>Read</fullName>
        <label>Read Only</label>
    </customValue>
    <customValue>
        <fullName>None</fullName>
        <label>No Access</label>
    </customValue>
    <masterLabel>Access Levels</masterLabel>
</GlobalValueSet>

classes/TerritorySharingSelector.cls
public with sharing class TerritorySharingSelector {
    
    public static List<TerritorySharingWrapper> getDuplicateSharings(Territory_Sharing__c sharing) {
        
        Map<Id, Territory_Sharing__c> duplicateSharings =  new Map<Id, Territory_Sharing__c>([
            SELECT Id, (
            		SELECT Id, RecordType.DeveloperName, Territory_Sharing__c, Field_API_Name__c, Operator__c, Field_Value__c
                    FROM Territory_Sharing_Criteria__r
                    ORDER BY CreatedDate ASC
                    LIMIT 20
            	)
            FROM Territory_Sharing__c
            WHERE (Business_Unit__c = :sharing.Business_Unit__c  AND
                   Group_Id_To_Share_Record_With__c = :sharing.Group_Id_To_Share_Record_With__c) 
            LIMIT 1000
        ]);
        
        if (sharing.Id != null) {
			duplicateSharings.remove(sharing.Id);
        }
        return wrapSharingRulesAndCriteria(duplicateSharings.values());
    }
    
    public static List<TerritorySharingWrapper> getTerritorySharingsWithCriteria(Map<Id, Territory_Sharing__c> sharings) {
        
        List<TerritorySharingWrapper> sharingWrappers = new List<TerritorySharingWrapper>();
       
        for (Territory_Sharing__c sharing : [
            SELECT ID, Name,
                (
                    SELECT Id, RecordType.DeveloperName, Territory_Sharing__c, Field_API_Name__c, Operator__c, Field_Value__c
                    FROM Territory_Sharing_Criteria__r
                    ORDER BY CreatedDate ASC
                    LIMIT 20
                )
            FROM Territory_Sharing__c
            WHERE ID IN :sharings.keySet()
            LIMIT 10000
        ]) { 
            sharingWrappers.add(new TerritorySharingWrapper(sharings.get(sharing.Id), sharing.Territory_Sharing_Criteria__r));
        }
        return sharingWrappers;
    }

    public static List<Territory_Sharing_Criterion__c> getTerritorySharingCriteria(Id sharingId, String criteriaName) {

        return [
            SELECT Id, RecordType.DeveloperName, Territory_Sharing__c, 
                Field_API_Name__c, Operator__c, Field_Value__c
            FROM Territory_Sharing_Criterion__c
            WHERE (RecordType.DeveloperName = :criteriaName
                AND  Territory_Sharing__c = :sharingId)
            ORDER BY CreatedDate ASC
            LIMIT 1000
        ];
    }
    
    public static TerritorySharingWrapper getSharingById(Id sharingId) {
        
        Territory_Sharing__c sharing = [
            SELECT ID, Name,Business_Unit__c , Group_Id_To_Share_Record_With__c,
                    Account_Access_Level__c, Lead_Access_Level__c, Case_Access_Level__c, Contact_Access_Level__c,
                    Opportunity_Access_Level__c, Device_Access_Level__c, Services_Demos_Access_Level__c, Activity_Access_Level__c,
                (
                    SELECT Id, RecordType.DeveloperName, Territory_Sharing__c, Field_API_Name__c, Operator__c, Field_Value__c
                    FROM Territory_Sharing_Criteria__r
                    ORDER BY CreatedDate ASC
                    LIMIT 20
                )
            FROM Territory_Sharing__c
            WHERE ID = :sharingId
            LIMIT 1
        ];
        
        return new TerritorySharingWrapper(sharing, sharing.Territory_Sharing_Criteria__r);
    }
    
    public static List<TerritorySharingWrapper> getTerritorySharingsByBusinessUnitAndGroupId(String businessUnit, String groupId) {

        List<TerritorySharingWrapper> sharings = new List<TerritorySharingWrapper>();
        
        for(Territory_Sharing__c sharing : [
                SELECT Id, Name, Business_Unit__c , Group_Id_To_Share_Record_With__c, 
                    Account_Access_Level__c, Lead_Access_Level__c, Case_Access_Level__c, Contact_Access_Level__c,
                    Opportunity_Access_Level__c, Device_Access_Level__c, Services_Demos_Access_Level__c, Activity_Access_Level__c,
                (
                    SELECT Id, RecordType.DeveloperName, Territory_Sharing__c, Field_API_Name__c, Operator__c, Field_Value__c
                    FROM Territory_Sharing_Criteria__r 
                    ORDER BY CreatedDate ASC
                    LIMIT 20
                )
                FROM Territory_Sharing__c
                WHERE (Business_Unit__c = :businessUnit
                    AND Group_Id_To_Share_Record_With__c = :groupId)
                LIMIT 200
        ] ) {
            sharings.add(new TerritorySharingWrapper(sharing, sharing.Territory_Sharing_Criteria__r));
        }
        return sharings;
    }
    
    public static List<TerritorySharingWrapper> wrapSharingRulesAndCriteria(List<Territory_Sharing__c> sharings) {
        
        List<TerritorySharingWrapper> sharingWrappers = new List<TerritorySharingWrapper>();

		for (Territory_Sharing__c sharing : sharings) {
			sharingWrappers.add(new TerritorySharingWrapper(sharing, sharing.Territory_Sharing_Criteria__r));
		}
        return sharingWrappers;
    }
}