objects/Territory_Sharing_Criterion__c.object
<CustomObject>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>equals</fullName>
                    <default>true</default>
                    <label>equals</label>
                </value>
                <value>
                    <fullName>includes</fullName>
                </value>
                <value>
                    <fullName>starts with</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PT - Territory Sharing Criterion</label>
    <nameField>
        <displayFormat>TSC-{000000}</displayFormat>
        <label>Territory Sharing Criterion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Sharing Criterion</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Variable.cls
public with sharing class Variable implements Expression {
     
    private sObject objectToCheckSharing;
    private Territory_Sharing_Criterion__c criterium;
    private String classToProcessOperation; 
        
    public Variable(Territory_Sharing_Criterion__c criterium){ 
        this.criterium = criterium; 
        this.classToProcessOperation = SharingConstants.OPERATION_CLASS_BY_OBJECT.get(this.criterium.Operator__c);
    }

    public Expression add(Expression expr){ 
        return this; 
    }
    
    public Expression set(SObject objectToCheckSharing){ 
        this.objectToCheckSharing = objectToCheckSharing;
		return this; 
    }
    
	public Boolean evaluate() { 
        
        if (String.isNotBlank(this.classToProcessOperation) && this.objectToCheckSharing != null)  {
            Type t = Type.forName(this.classToProcessOperation);
        	IOperator operator = (IOperator)t.newInstance();
        	return operator.isMatchCriterion(this.objectToCheckSharing, this.criterium);    
        }
        return false;
    }
}