objects/Territory_Sharing__c.object
<CustomObject>
    <label>PT - Territory Sharing</label>
    <nameField>
        <label>Territory Sharing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Sharing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory_Sharing_Criterion__c.object
<CustomObject>
    <fields>
        <fullName>Territory_Sharing__c</fullName>
        <label>Territory Sharing</label>
        <referenceTo>Territory_Sharing__c</referenceTo>
        <relationshipName>Territory_Sharing_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PT - Territory Sharing Criterion</label>
    <nameField>
        <displayFormat>TSC-{000000}</displayFormat>
        <label>Territory Sharing Criterion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Sharing Criterion</pluralLabel>
    <recordTypes>
        <fullName>Account_Criteria</fullName>
        <active>true</active>
        <description>Territory sharing criteria for Account object</description>
        <label>Account Criteria</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lead_Criteria</fullName>
        <active>true</active>
        <description>Territory sharing criteria for Lead object</description>
        <label>Lead Criteria</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TerritorySharingWrapper.cls
public with sharing class TerritorySharingWrapper {
    
    public Territory_Sharing__c sharing { get; set; }
    public List<Territory_Sharing_Criterion__c> criteria { get; set; }
    public List<Territory_Sharing_Criterion__c> accountCriteria { get; set; }
    public List<Territory_Sharing_Criterion__c> leadCriteria { get; set; }
    
    public TerritorySharingWrapper(Territory_Sharing__c sharing, List<Territory_Sharing_Criterion__c> criteria) {
        this.sharing = sharing;
        this.criteria = criteria;
        this.accountCriteria = filterCriteria(criteria, SharingConstants.ACCOUNT_CRITERIA);
        this.leadCriteria = filterCriteria(criteria, SharingConstants.LEAD_CRITERIA);
    }
    
    private List<Territory_Sharing_Criterion__c> filterCriteria(List<Territory_Sharing_Criterion__c> criteria, String criterionName) {

        List<Territory_Sharing_Criterion__c> filteredCriteria = new List<Territory_Sharing_Criterion__c>();

        for (Territory_Sharing_Criterion__c criterion : criteria) {

            if (criterion.RecordType.DeveloperName.equals(criterionName)) {
                filteredCriteria.add(criterion);
            }
        }
        return filteredCriteria;
    }
    
    public List<Territory_Sharing_Criterion__c> getCriteriaByObjectName(String objectName) {
        
        if (objectName == SharingConstants.ACCOUNT_OBJECT) {
            return this.accountCriteria;
        }
        return this.leadCriteria;
    }
}