objects/Territory_Sharing__c.object
<CustomObject>
    <label>PT - Territory Sharing</label>
    <nameField>
        <label>Territory Sharing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Sharing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory_Sharing_Criterion__c.object
<CustomObject>
    <fields>
        <fullName>Territory_Sharing__c</fullName>
        <label>Territory Sharing</label>
        <referenceTo>Territory_Sharing__c</referenceTo>
        <relationshipName>Territory_Sharing_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PT - Territory Sharing Criterion</label>
    <nameField>
        <displayFormat>TSC-{000000}</displayFormat>
        <label>Territory Sharing Criterion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Sharing Criterion</pluralLabel>
    <recordTypes>
        <fullName>Account_Criteria</fullName>
        <active>true</active>
        <description>Territory sharing criteria for Account object</description>
        <label>Account Criteria</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lead_Criteria</fullName>
        <active>true</active>
        <description>Territory sharing criteria for Lead object</description>
        <label>Lead Criteria</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TerritorySharingViewExtension.cls
public with sharing class TerritorySharingViewExtension {

    public ApexPages.StandardController cntr { get; set; }
    public List<Territory_Sharing_Criterion__c> leadCriteria { get; set; }
    public List<Territory_Sharing_Criterion__c> accountCriteria { get; set; }
    
    public TerritorySharingViewExtension(ApexPages.StandardController cntr) {
        this.cntr = cntr;
		this.leadCriteria = TerritorySharingSelector.getTerritorySharingCriteria(cntr.getId(), SharingConstants.LEAD_CRITERIA);
        this.accountCriteria = TerritorySharingSelector.getTerritorySharingCriteria(cntr.getId(), SharingConstants.ACCOUNT_CRITERIA);
    }
    
    public PageReference recalculate() {
        PageReference page = cntr.edit();
        page.setRedirect(true);
        return page;
    }
    
 	public PageReference back() {
		Schema.DescribeSObjectResult result = Territory_Sharing__c.SObjectType.getDescribe(); 
        PageReference pageRef = new PageReference('/' + result.getKeyPrefix()); 
        pageRef.setRedirect(true); 
        return pageRef; 
    }
}